/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDashboardDto } from './AdminDashboardDto';
import {
    AdminDashboardDtoFromJSON,
    AdminDashboardDtoFromJSONTyped,
    AdminDashboardDtoToJSON,
    AdminDashboardDtoToJSONTyped,
} from './AdminDashboardDto';

/**
 * 
 * @export
 * @interface AdminDashboardApiResponseDto
 */
export interface AdminDashboardApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminDashboardApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminDashboardDto}
     * @memberof AdminDashboardApiResponseDto
     */
    data: AdminDashboardDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminDashboardApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminDashboardApiResponseDto interface.
 */
export function instanceOfAdminDashboardApiResponseDto(value: object): value is AdminDashboardApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminDashboardApiResponseDtoFromJSON(json: any): AdminDashboardApiResponseDto {
    return AdminDashboardApiResponseDtoFromJSONTyped(json, false);
}

export function AdminDashboardApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDashboardApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminDashboardDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminDashboardApiResponseDtoToJSON(json: any): AdminDashboardApiResponseDto {
    return AdminDashboardApiResponseDtoToJSONTyped(json, false);
}

export function AdminDashboardApiResponseDtoToJSONTyped(value?: AdminDashboardApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminDashboardDtoToJSON(value['data']),
        'error': value['error'],
    };
}

