/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminNotificationDto } from './AdminNotificationDto';
import {
    AdminNotificationDtoFromJSON,
    AdminNotificationDtoFromJSONTyped,
    AdminNotificationDtoToJSON,
    AdminNotificationDtoToJSONTyped,
} from './AdminNotificationDto';

/**
 * 
 * @export
 * @interface AdminNotificationApiResponseDto
 */
export interface AdminNotificationApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminNotificationApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminNotificationDto}
     * @memberof AdminNotificationApiResponseDto
     */
    data: AdminNotificationDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminNotificationApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminNotificationApiResponseDto interface.
 */
export function instanceOfAdminNotificationApiResponseDto(value: object): value is AdminNotificationApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminNotificationApiResponseDtoFromJSON(json: any): AdminNotificationApiResponseDto {
    return AdminNotificationApiResponseDtoFromJSONTyped(json, false);
}

export function AdminNotificationApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminNotificationApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminNotificationDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminNotificationApiResponseDtoToJSON(json: any): AdminNotificationApiResponseDto {
    return AdminNotificationApiResponseDtoToJSONTyped(json, false);
}

export function AdminNotificationApiResponseDtoToJSONTyped(value?: AdminNotificationApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminNotificationDtoToJSON(value['data']),
        'error': value['error'],
    };
}

