/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminNotificationDto
 */
export interface AdminNotificationDto {
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    channel: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    recipientEmail?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminNotificationDto
     */
    attempts: number;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    lastError?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    processedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the AdminNotificationDto interface.
 */
export function instanceOfAdminNotificationDto(value: object): value is AdminNotificationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminNotificationDtoFromJSON(json: any): AdminNotificationDto {
    return AdminNotificationDtoFromJSONTyped(json, false);
}

export function AdminNotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminNotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'channel': json['channel'],
        'status': json['status'],
        'recipientEmail': json['recipient_email'] == null ? undefined : json['recipient_email'],
        'attempts': json['attempts'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'lastError': json['last_error'] == null ? undefined : json['last_error'],
        'processedAt': json['processed_at'] == null ? undefined : json['processed_at'],
        'createdAt': json['created_at'],
    };
}

export function AdminNotificationDtoToJSON(json: any): AdminNotificationDto {
    return AdminNotificationDtoToJSONTyped(json, false);
}

export function AdminNotificationDtoToJSONTyped(value?: AdminNotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'channel': value['channel'],
        'status': value['status'],
        'recipient_email': value['recipientEmail'],
        'attempts': value['attempts'],
        'provider': value['provider'],
        'last_error': value['lastError'],
        'processed_at': value['processedAt'],
        'created_at': value['createdAt'],
    };
}

