/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminPlatformReportSummaryDto } from './AdminPlatformReportSummaryDto';
import {
    AdminPlatformReportSummaryDtoFromJSON,
    AdminPlatformReportSummaryDtoFromJSONTyped,
    AdminPlatformReportSummaryDtoToJSON,
    AdminPlatformReportSummaryDtoToJSONTyped,
} from './AdminPlatformReportSummaryDto';

/**
 * 
 * @export
 * @interface AdminPlatformReportSummaryApiResponseDto
 */
export interface AdminPlatformReportSummaryApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminPlatformReportSummaryApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminPlatformReportSummaryApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPlatformReportSummaryApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminPlatformReportSummaryDto}
     * @memberof AdminPlatformReportSummaryApiResponseDto
     */
    data: AdminPlatformReportSummaryDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminPlatformReportSummaryApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminPlatformReportSummaryApiResponseDto interface.
 */
export function instanceOfAdminPlatformReportSummaryApiResponseDto(value: object): value is AdminPlatformReportSummaryApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminPlatformReportSummaryApiResponseDtoFromJSON(json: any): AdminPlatformReportSummaryApiResponseDto {
    return AdminPlatformReportSummaryApiResponseDtoFromJSONTyped(json, false);
}

export function AdminPlatformReportSummaryApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPlatformReportSummaryApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminPlatformReportSummaryDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminPlatformReportSummaryApiResponseDtoToJSON(json: any): AdminPlatformReportSummaryApiResponseDto {
    return AdminPlatformReportSummaryApiResponseDtoToJSONTyped(json, false);
}

export function AdminPlatformReportSummaryApiResponseDtoToJSONTyped(value?: AdminPlatformReportSummaryApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminPlatformReportSummaryDtoToJSON(value['data']),
        'error': value['error'],
    };
}

