/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminPaymentEventDto
 */
export interface AdminPaymentEventDto {
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentEventDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentEventDto
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentEventDto
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentEventDto
     */
    providerEventId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminPaymentEventDto
     */
    signatureValid?: boolean | null;
    /**
     * 
     * @type {object}
     * @memberof AdminPaymentEventDto
     */
    payloadSummary: object;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentEventDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the AdminPaymentEventDto interface.
 */
export function instanceOfAdminPaymentEventDto(value: object): value is AdminPaymentEventDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('payloadSummary' in value) || value['payloadSummary'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminPaymentEventDtoFromJSON(json: any): AdminPaymentEventDto {
    return AdminPaymentEventDtoFromJSONTyped(json, false);
}

export function AdminPaymentEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPaymentEventDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'eventType': json['event_type'],
        'providerEventId': json['provider_event_id'] == null ? undefined : json['provider_event_id'],
        'signatureValid': json['signature_valid'] == null ? undefined : json['signature_valid'],
        'payloadSummary': json['payload_summary'],
        'createdAt': json['created_at'],
    };
}

export function AdminPaymentEventDtoToJSON(json: any): AdminPaymentEventDto {
    return AdminPaymentEventDtoToJSONTyped(json, false);
}

export function AdminPaymentEventDtoToJSONTyped(value?: AdminPaymentEventDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'event_type': value['eventType'],
        'provider_event_id': value['providerEventId'],
        'signature_valid': value['signatureValid'],
        'payload_summary': value['payloadSummary'],
        'created_at': value['createdAt'],
    };
}

