/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOrganizerDto } from './AdminOrganizerDto';
import {
    AdminOrganizerDtoFromJSON,
    AdminOrganizerDtoFromJSONTyped,
    AdminOrganizerDtoToJSON,
    AdminOrganizerDtoToJSONTyped,
} from './AdminOrganizerDto';

/**
 * 
 * @export
 * @interface AdminOrganizerApiResponseDto
 */
export interface AdminOrganizerApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizerApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizerApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizerApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminOrganizerDto}
     * @memberof AdminOrganizerApiResponseDto
     */
    data: AdminOrganizerDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminOrganizerApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminOrganizerApiResponseDto interface.
 */
export function instanceOfAdminOrganizerApiResponseDto(value: object): value is AdminOrganizerApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminOrganizerApiResponseDtoFromJSON(json: any): AdminOrganizerApiResponseDto {
    return AdminOrganizerApiResponseDtoFromJSONTyped(json, false);
}

export function AdminOrganizerApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizerApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminOrganizerDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminOrganizerApiResponseDtoToJSON(json: any): AdminOrganizerApiResponseDto {
    return AdminOrganizerApiResponseDtoToJSONTyped(json, false);
}

export function AdminOrganizerApiResponseDtoToJSONTyped(value?: AdminOrganizerApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminOrganizerDtoToJSON(value['data']),
        'error': value['error'],
    };
}

