/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOperationsDependencyDto
 */
export interface AdminOperationsDependencyDto {
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsDependencyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsDependencyDto
     */
    status: string;
}

/**
 * Check if a given object implements the AdminOperationsDependencyDto interface.
 */
export function instanceOfAdminOperationsDependencyDto(value: object): value is AdminOperationsDependencyDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AdminOperationsDependencyDtoFromJSON(json: any): AdminOperationsDependencyDto {
    return AdminOperationsDependencyDtoFromJSONTyped(json, false);
}

export function AdminOperationsDependencyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOperationsDependencyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
    };
}

export function AdminOperationsDependencyDtoToJSON(json: any): AdminOperationsDependencyDto {
    return AdminOperationsDependencyDtoToJSONTyped(json, false);
}

export function AdminOperationsDependencyDtoToJSONTyped(value?: AdminOperationsDependencyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
    };
}

