/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUserSummaryDto
 */
export interface AdminUserSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof AdminUserSummaryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserSummaryDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserSummaryDto
     */
    displayName: string;
}

/**
 * Check if a given object implements the AdminUserSummaryDto interface.
 */
export function instanceOfAdminUserSummaryDto(value: object): value is AdminUserSummaryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function AdminUserSummaryDtoFromJSON(json: any): AdminUserSummaryDto {
    return AdminUserSummaryDtoFromJSONTyped(json, false);
}

export function AdminUserSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'displayName': json['display_name'],
    };
}

export function AdminUserSummaryDtoToJSON(json: any): AdminUserSummaryDto {
    return AdminUserSummaryDtoToJSONTyped(json, false);
}

export function AdminUserSummaryDtoToJSONTyped(value?: AdminUserSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'display_name': value['displayName'],
    };
}

