/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOperationsThresholdDto
 */
export interface AdminOperationsThresholdDto {
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsThresholdDto
     */
    staleNotificationMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsThresholdDto
     */
    stalePaymentIntentMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsThresholdDto
     */
    failedNotificationAlertThreshold: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsThresholdDto
     */
    failedPaymentAlertThreshold: number;
}

/**
 * Check if a given object implements the AdminOperationsThresholdDto interface.
 */
export function instanceOfAdminOperationsThresholdDto(value: object): value is AdminOperationsThresholdDto {
    if (!('staleNotificationMinutes' in value) || value['staleNotificationMinutes'] === undefined) return false;
    if (!('stalePaymentIntentMinutes' in value) || value['stalePaymentIntentMinutes'] === undefined) return false;
    if (!('failedNotificationAlertThreshold' in value) || value['failedNotificationAlertThreshold'] === undefined) return false;
    if (!('failedPaymentAlertThreshold' in value) || value['failedPaymentAlertThreshold'] === undefined) return false;
    return true;
}

export function AdminOperationsThresholdDtoFromJSON(json: any): AdminOperationsThresholdDto {
    return AdminOperationsThresholdDtoFromJSONTyped(json, false);
}

export function AdminOperationsThresholdDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOperationsThresholdDto {
    if (json == null) {
        return json;
    }
    return {
        
        'staleNotificationMinutes': json['stale_notification_minutes'],
        'stalePaymentIntentMinutes': json['stale_payment_intent_minutes'],
        'failedNotificationAlertThreshold': json['failed_notification_alert_threshold'],
        'failedPaymentAlertThreshold': json['failed_payment_alert_threshold'],
    };
}

export function AdminOperationsThresholdDtoToJSON(json: any): AdminOperationsThresholdDto {
    return AdminOperationsThresholdDtoToJSONTyped(json, false);
}

export function AdminOperationsThresholdDtoToJSONTyped(value?: AdminOperationsThresholdDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stale_notification_minutes': value['staleNotificationMinutes'],
        'stale_payment_intent_minutes': value['stalePaymentIntentMinutes'],
        'failed_notification_alert_threshold': value['failedNotificationAlertThreshold'],
        'failed_payment_alert_threshold': value['failedPaymentAlertThreshold'],
    };
}

