/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminPaymentDto } from './AdminPaymentDto';
import {
    AdminPaymentDtoFromJSON,
    AdminPaymentDtoFromJSONTyped,
    AdminPaymentDtoToJSON,
    AdminPaymentDtoToJSONTyped,
} from './AdminPaymentDto';
import type { AdminPaginationDto } from './AdminPaginationDto';
import {
    AdminPaginationDtoFromJSON,
    AdminPaginationDtoFromJSONTyped,
    AdminPaginationDtoToJSON,
    AdminPaginationDtoToJSONTyped,
} from './AdminPaginationDto';

/**
 * 
 * @export
 * @interface AdminPaymentListDto
 */
export interface AdminPaymentListDto {
    /**
     * 
     * @type {Array<AdminPaymentDto>}
     * @memberof AdminPaymentListDto
     */
    items: Array<AdminPaymentDto>;
    /**
     * 
     * @type {AdminPaginationDto}
     * @memberof AdminPaymentListDto
     */
    pagination: AdminPaginationDto;
}

/**
 * Check if a given object implements the AdminPaymentListDto interface.
 */
export function instanceOfAdminPaymentListDto(value: object): value is AdminPaymentListDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AdminPaymentListDtoFromJSON(json: any): AdminPaymentListDto {
    return AdminPaymentListDtoFromJSONTyped(json, false);
}

export function AdminPaymentListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPaymentListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminPaymentDtoFromJSON)),
        'pagination': AdminPaginationDtoFromJSON(json['pagination']),
    };
}

export function AdminPaymentListDtoToJSON(json: any): AdminPaymentListDto {
    return AdminPaymentListDtoToJSONTyped(json, false);
}

export function AdminPaymentListDtoToJSONTyped(value?: AdminPaymentListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminPaymentDtoToJSON)),
        'pagination': AdminPaginationDtoToJSON(value['pagination']),
    };
}

