/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserSummaryDto } from './AdminUserSummaryDto';
import {
    AdminUserSummaryDtoFromJSON,
    AdminUserSummaryDtoFromJSONTyped,
    AdminUserSummaryDtoToJSON,
    AdminUserSummaryDtoToJSONTyped,
} from './AdminUserSummaryDto';

/**
 * 
 * @export
 * @interface AdminRegistrationDto
 */
export interface AdminRegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    id: string;
    /**
     * 
     * @type {AdminUserSummaryDto}
     * @memberof AdminRegistrationDto
     */
    player: AdminUserSummaryDto;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    tournamentId: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    tournamentTitle: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    paymentStatus: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRegistrationDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the AdminRegistrationDto interface.
 */
export function instanceOfAdminRegistrationDto(value: object): value is AdminRegistrationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('player' in value) || value['player'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('tournamentId' in value) || value['tournamentId'] === undefined) return false;
    if (!('tournamentTitle' in value) || value['tournamentTitle'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminRegistrationDtoFromJSON(json: any): AdminRegistrationDto {
    return AdminRegistrationDtoFromJSONTyped(json, false);
}

export function AdminRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRegistrationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'player': AdminUserSummaryDtoFromJSON(json['player']),
        'playerName': json['player_name'],
        'tournamentId': json['tournament_id'],
        'tournamentTitle': json['tournament_title'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'status': json['status'],
        'paymentStatus': json['payment_status'],
        'createdAt': json['created_at'],
    };
}

export function AdminRegistrationDtoToJSON(json: any): AdminRegistrationDto {
    return AdminRegistrationDtoToJSONTyped(json, false);
}

export function AdminRegistrationDtoToJSONTyped(value?: AdminRegistrationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'player': AdminUserSummaryDtoToJSON(value['player']),
        'player_name': value['playerName'],
        'tournament_id': value['tournamentId'],
        'tournament_title': value['tournamentTitle'],
        'category_name': value['categoryName'],
        'status': value['status'],
        'payment_status': value['paymentStatus'],
        'created_at': value['createdAt'],
    };
}

