/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminRegistrationDto } from './AdminRegistrationDto';
import {
    AdminRegistrationDtoFromJSON,
    AdminRegistrationDtoFromJSONTyped,
    AdminRegistrationDtoToJSON,
    AdminRegistrationDtoToJSONTyped,
} from './AdminRegistrationDto';
import type { AdminPaginationDto } from './AdminPaginationDto';
import {
    AdminPaginationDtoFromJSON,
    AdminPaginationDtoFromJSONTyped,
    AdminPaginationDtoToJSON,
    AdminPaginationDtoToJSONTyped,
} from './AdminPaginationDto';

/**
 * 
 * @export
 * @interface AdminRegistrationListDto
 */
export interface AdminRegistrationListDto {
    /**
     * 
     * @type {Array<AdminRegistrationDto>}
     * @memberof AdminRegistrationListDto
     */
    items: Array<AdminRegistrationDto>;
    /**
     * 
     * @type {AdminPaginationDto}
     * @memberof AdminRegistrationListDto
     */
    pagination: AdminPaginationDto;
}

/**
 * Check if a given object implements the AdminRegistrationListDto interface.
 */
export function instanceOfAdminRegistrationListDto(value: object): value is AdminRegistrationListDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AdminRegistrationListDtoFromJSON(json: any): AdminRegistrationListDto {
    return AdminRegistrationListDtoFromJSONTyped(json, false);
}

export function AdminRegistrationListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRegistrationListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminRegistrationDtoFromJSON)),
        'pagination': AdminPaginationDtoFromJSON(json['pagination']),
    };
}

export function AdminRegistrationListDtoToJSON(json: any): AdminRegistrationListDto {
    return AdminRegistrationListDtoToJSONTyped(json, false);
}

export function AdminRegistrationListDtoToJSONTyped(value?: AdminRegistrationListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminRegistrationDtoToJSON)),
        'pagination': AdminPaginationDtoToJSON(value['pagination']),
    };
}

