/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserOrganizerSummaryDto } from './AdminUserOrganizerSummaryDto';
import {
    AdminUserOrganizerSummaryDtoFromJSON,
    AdminUserOrganizerSummaryDtoFromJSONTyped,
    AdminUserOrganizerSummaryDtoToJSON,
    AdminUserOrganizerSummaryDtoToJSONTyped,
} from './AdminUserOrganizerSummaryDto';

/**
 * 
 * @export
 * @interface AdminUserDto
 */
export interface AdminUserDto {
    /**
     * 
     * @type {string}
     * @memberof AdminUserDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDto
     */
    displayName: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserDto
     */
    roles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDto
     */
    status: string;
    /**
     * 
     * @type {AdminUserOrganizerSummaryDto}
     * @memberof AdminUserDto
     */
    organizer?: AdminUserOrganizerSummaryDto | null;
    /**
     * 
     * @type {number}
     * @memberof AdminUserDto
     */
    registrationCount: number;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the AdminUserDto interface.
 */
export function instanceOfAdminUserDto(value: object): value is AdminUserDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('registrationCount' in value) || value['registrationCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminUserDtoFromJSON(json: any): AdminUserDto {
    return AdminUserDtoFromJSONTyped(json, false);
}

export function AdminUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'displayName': json['display_name'],
        'roles': json['roles'],
        'status': json['status'],
        'organizer': json['organizer'] == null ? undefined : AdminUserOrganizerSummaryDtoFromJSON(json['organizer']),
        'registrationCount': json['registration_count'],
        'createdAt': json['created_at'],
    };
}

export function AdminUserDtoToJSON(json: any): AdminUserDto {
    return AdminUserDtoToJSONTyped(json, false);
}

export function AdminUserDtoToJSONTyped(value?: AdminUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'display_name': value['displayName'],
        'roles': value['roles'],
        'status': value['status'],
        'organizer': AdminUserOrganizerSummaryDtoToJSON(value['organizer']),
        'registration_count': value['registrationCount'],
        'created_at': value['createdAt'],
    };
}

