/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminNotificationListDto } from './AdminNotificationListDto';
import {
    AdminNotificationListDtoFromJSON,
    AdminNotificationListDtoFromJSONTyped,
    AdminNotificationListDtoToJSON,
    AdminNotificationListDtoToJSONTyped,
} from './AdminNotificationListDto';

/**
 * 
 * @export
 * @interface AdminNotificationsApiResponseDto
 */
export interface AdminNotificationsApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminNotificationsApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationsApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminNotificationsApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminNotificationListDto}
     * @memberof AdminNotificationsApiResponseDto
     */
    data: AdminNotificationListDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminNotificationsApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminNotificationsApiResponseDto interface.
 */
export function instanceOfAdminNotificationsApiResponseDto(value: object): value is AdminNotificationsApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminNotificationsApiResponseDtoFromJSON(json: any): AdminNotificationsApiResponseDto {
    return AdminNotificationsApiResponseDtoFromJSONTyped(json, false);
}

export function AdminNotificationsApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminNotificationsApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminNotificationListDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminNotificationsApiResponseDtoToJSON(json: any): AdminNotificationsApiResponseDto {
    return AdminNotificationsApiResponseDtoToJSONTyped(json, false);
}

export function AdminNotificationsApiResponseDtoToJSONTyped(value?: AdminNotificationsApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminNotificationListDtoToJSON(value['data']),
        'error': value['error'],
    };
}

