/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminNotificationDto } from './AdminNotificationDto';
import {
    AdminNotificationDtoFromJSON,
    AdminNotificationDtoFromJSONTyped,
    AdminNotificationDtoToJSON,
    AdminNotificationDtoToJSONTyped,
} from './AdminNotificationDto';
import type { AdminPaginationDto } from './AdminPaginationDto';
import {
    AdminPaginationDtoFromJSON,
    AdminPaginationDtoFromJSONTyped,
    AdminPaginationDtoToJSON,
    AdminPaginationDtoToJSONTyped,
} from './AdminPaginationDto';

/**
 * 
 * @export
 * @interface AdminNotificationListDto
 */
export interface AdminNotificationListDto {
    /**
     * 
     * @type {Array<AdminNotificationDto>}
     * @memberof AdminNotificationListDto
     */
    items: Array<AdminNotificationDto>;
    /**
     * 
     * @type {AdminPaginationDto}
     * @memberof AdminNotificationListDto
     */
    pagination: AdminPaginationDto;
}

/**
 * Check if a given object implements the AdminNotificationListDto interface.
 */
export function instanceOfAdminNotificationListDto(value: object): value is AdminNotificationListDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AdminNotificationListDtoFromJSON(json: any): AdminNotificationListDto {
    return AdminNotificationListDtoFromJSONTyped(json, false);
}

export function AdminNotificationListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminNotificationListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminNotificationDtoFromJSON)),
        'pagination': AdminPaginationDtoFromJSON(json['pagination']),
    };
}

export function AdminNotificationListDtoToJSON(json: any): AdminNotificationListDto {
    return AdminNotificationListDtoToJSONTyped(json, false);
}

export function AdminNotificationListDtoToJSONTyped(value?: AdminNotificationListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminNotificationDtoToJSON)),
        'pagination': AdminPaginationDtoToJSON(value['pagination']),
    };
}

