/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminPaymentListDto } from './AdminPaymentListDto';
import {
    AdminPaymentListDtoFromJSON,
    AdminPaymentListDtoFromJSONTyped,
    AdminPaymentListDtoToJSON,
    AdminPaymentListDtoToJSONTyped,
} from './AdminPaymentListDto';

/**
 * 
 * @export
 * @interface AdminPaymentsApiResponseDto
 */
export interface AdminPaymentsApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminPaymentsApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentsApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentsApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminPaymentListDto}
     * @memberof AdminPaymentsApiResponseDto
     */
    data: AdminPaymentListDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminPaymentsApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminPaymentsApiResponseDto interface.
 */
export function instanceOfAdminPaymentsApiResponseDto(value: object): value is AdminPaymentsApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminPaymentsApiResponseDtoFromJSON(json: any): AdminPaymentsApiResponseDto {
    return AdminPaymentsApiResponseDtoFromJSONTyped(json, false);
}

export function AdminPaymentsApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPaymentsApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminPaymentListDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminPaymentsApiResponseDtoToJSON(json: any): AdminPaymentsApiResponseDto {
    return AdminPaymentsApiResponseDtoToJSONTyped(json, false);
}

export function AdminPaymentsApiResponseDtoToJSONTyped(value?: AdminPaymentsApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminPaymentListDtoToJSON(value['data']),
        'error': value['error'],
    };
}

