/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOperationsLatestReconciliationDto } from './AdminOperationsLatestReconciliationDto';
import {
    AdminOperationsLatestReconciliationDtoFromJSON,
    AdminOperationsLatestReconciliationDtoFromJSONTyped,
    AdminOperationsLatestReconciliationDtoToJSON,
    AdminOperationsLatestReconciliationDtoToJSONTyped,
} from './AdminOperationsLatestReconciliationDto';
import type { AdminOperationsThresholdDto } from './AdminOperationsThresholdDto';
import {
    AdminOperationsThresholdDtoFromJSON,
    AdminOperationsThresholdDtoFromJSONTyped,
    AdminOperationsThresholdDtoToJSON,
    AdminOperationsThresholdDtoToJSONTyped,
} from './AdminOperationsThresholdDto';
import type { AdminOperationsDependencyDto } from './AdminOperationsDependencyDto';
import {
    AdminOperationsDependencyDtoFromJSON,
    AdminOperationsDependencyDtoFromJSONTyped,
    AdminOperationsDependencyDtoToJSON,
    AdminOperationsDependencyDtoToJSONTyped,
} from './AdminOperationsDependencyDto';

/**
 * 
 * @export
 * @interface AdminOperationsStatusDto
 */
export interface AdminOperationsStatusDto {
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    serviceName: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    appVersion: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    checkedAt: string;
    /**
     * 
     * @type {Array<AdminOperationsDependencyDto>}
     * @memberof AdminOperationsStatusDto
     */
    dependencies: Array<AdminOperationsDependencyDto>;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    paymentProvider: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOperationsStatusDto
     */
    notificationProvider: string;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    exportMaxRows: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    pendingNotifications: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    failedNotifications: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    staleProcessingNotifications: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    stalePaymentIntents: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    failedPaymentIntents: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOperationsStatusDto
     */
    failedPaymentEvents: number;
    /**
     * 
     * @type {AdminOperationsLatestReconciliationDto}
     * @memberof AdminOperationsStatusDto
     */
    latestReconciliationRun: AdminOperationsLatestReconciliationDto;
    /**
     * 
     * @type {AdminOperationsThresholdDto}
     * @memberof AdminOperationsStatusDto
     */
    thresholds: AdminOperationsThresholdDto;
}

/**
 * Check if a given object implements the AdminOperationsStatusDto interface.
 */
export function instanceOfAdminOperationsStatusDto(value: object): value is AdminOperationsStatusDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('appVersion' in value) || value['appVersion'] === undefined) return false;
    if (!('checkedAt' in value) || value['checkedAt'] === undefined) return false;
    if (!('dependencies' in value) || value['dependencies'] === undefined) return false;
    if (!('paymentProvider' in value) || value['paymentProvider'] === undefined) return false;
    if (!('notificationProvider' in value) || value['notificationProvider'] === undefined) return false;
    if (!('exportMaxRows' in value) || value['exportMaxRows'] === undefined) return false;
    if (!('pendingNotifications' in value) || value['pendingNotifications'] === undefined) return false;
    if (!('failedNotifications' in value) || value['failedNotifications'] === undefined) return false;
    if (!('staleProcessingNotifications' in value) || value['staleProcessingNotifications'] === undefined) return false;
    if (!('stalePaymentIntents' in value) || value['stalePaymentIntents'] === undefined) return false;
    if (!('failedPaymentIntents' in value) || value['failedPaymentIntents'] === undefined) return false;
    if (!('failedPaymentEvents' in value) || value['failedPaymentEvents'] === undefined) return false;
    if (!('latestReconciliationRun' in value) || value['latestReconciliationRun'] === undefined) return false;
    if (!('thresholds' in value) || value['thresholds'] === undefined) return false;
    return true;
}

export function AdminOperationsStatusDtoFromJSON(json: any): AdminOperationsStatusDto {
    return AdminOperationsStatusDtoFromJSONTyped(json, false);
}

export function AdminOperationsStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOperationsStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'serviceName': json['service_name'],
        'appVersion': json['app_version'],
        'checkedAt': json['checked_at'],
        'dependencies': ((json['dependencies'] as Array<any>).map(AdminOperationsDependencyDtoFromJSON)),
        'paymentProvider': json['payment_provider'],
        'notificationProvider': json['notification_provider'],
        'exportMaxRows': json['export_max_rows'],
        'pendingNotifications': json['pending_notifications'],
        'failedNotifications': json['failed_notifications'],
        'staleProcessingNotifications': json['stale_processing_notifications'],
        'stalePaymentIntents': json['stale_payment_intents'],
        'failedPaymentIntents': json['failed_payment_intents'],
        'failedPaymentEvents': json['failed_payment_events'],
        'latestReconciliationRun': AdminOperationsLatestReconciliationDtoFromJSON(json['latest_reconciliation_run']),
        'thresholds': AdminOperationsThresholdDtoFromJSON(json['thresholds']),
    };
}

export function AdminOperationsStatusDtoToJSON(json: any): AdminOperationsStatusDto {
    return AdminOperationsStatusDtoToJSONTyped(json, false);
}

export function AdminOperationsStatusDtoToJSONTyped(value?: AdminOperationsStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service_name': value['serviceName'],
        'app_version': value['appVersion'],
        'checked_at': value['checkedAt'],
        'dependencies': ((value['dependencies'] as Array<any>).map(AdminOperationsDependencyDtoToJSON)),
        'payment_provider': value['paymentProvider'],
        'notification_provider': value['notificationProvider'],
        'export_max_rows': value['exportMaxRows'],
        'pending_notifications': value['pendingNotifications'],
        'failed_notifications': value['failedNotifications'],
        'stale_processing_notifications': value['staleProcessingNotifications'],
        'stale_payment_intents': value['stalePaymentIntents'],
        'failed_payment_intents': value['failedPaymentIntents'],
        'failed_payment_events': value['failedPaymentEvents'],
        'latest_reconciliation_run': AdminOperationsLatestReconciliationDtoToJSON(value['latestReconciliationRun']),
        'thresholds': AdminOperationsThresholdDtoToJSON(value['thresholds']),
    };
}

