/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReconciliationRunDto } from './AdminReconciliationRunDto';
import {
    AdminReconciliationRunDtoFromJSON,
    AdminReconciliationRunDtoFromJSONTyped,
    AdminReconciliationRunDtoToJSON,
    AdminReconciliationRunDtoToJSONTyped,
} from './AdminReconciliationRunDto';
import type { AdminPaginationDto } from './AdminPaginationDto';
import {
    AdminPaginationDtoFromJSON,
    AdminPaginationDtoFromJSONTyped,
    AdminPaginationDtoToJSON,
    AdminPaginationDtoToJSONTyped,
} from './AdminPaginationDto';

/**
 * 
 * @export
 * @interface AdminReconciliationRunListDto
 */
export interface AdminReconciliationRunListDto {
    /**
     * 
     * @type {Array<AdminReconciliationRunDto>}
     * @memberof AdminReconciliationRunListDto
     */
    items: Array<AdminReconciliationRunDto>;
    /**
     * 
     * @type {AdminPaginationDto}
     * @memberof AdminReconciliationRunListDto
     */
    pagination: AdminPaginationDto;
}

/**
 * Check if a given object implements the AdminReconciliationRunListDto interface.
 */
export function instanceOfAdminReconciliationRunListDto(value: object): value is AdminReconciliationRunListDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AdminReconciliationRunListDtoFromJSON(json: any): AdminReconciliationRunListDto {
    return AdminReconciliationRunListDtoFromJSONTyped(json, false);
}

export function AdminReconciliationRunListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReconciliationRunListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminReconciliationRunDtoFromJSON)),
        'pagination': AdminPaginationDtoFromJSON(json['pagination']),
    };
}

export function AdminReconciliationRunListDtoToJSON(json: any): AdminReconciliationRunListDto {
    return AdminReconciliationRunListDtoToJSONTyped(json, false);
}

export function AdminReconciliationRunListDtoToJSONTyped(value?: AdminReconciliationRunListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminReconciliationRunDtoToJSON)),
        'pagination': AdminPaginationDtoToJSON(value['pagination']),
    };
}

