/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminPaymentProviderStatusReportDto
 */
export interface AdminPaymentProviderStatusReportDto {
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentProviderStatusReportDto
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof AdminPaymentProviderStatusReportDto
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof AdminPaymentProviderStatusReportDto
     */
    count: number;
}

/**
 * Check if a given object implements the AdminPaymentProviderStatusReportDto interface.
 */
export function instanceOfAdminPaymentProviderStatusReportDto(value: object): value is AdminPaymentProviderStatusReportDto {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function AdminPaymentProviderStatusReportDtoFromJSON(json: any): AdminPaymentProviderStatusReportDto {
    return AdminPaymentProviderStatusReportDtoFromJSONTyped(json, false);
}

export function AdminPaymentProviderStatusReportDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPaymentProviderStatusReportDto {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'status': json['status'],
        'count': json['count'],
    };
}

export function AdminPaymentProviderStatusReportDtoToJSON(json: any): AdminPaymentProviderStatusReportDto {
    return AdminPaymentProviderStatusReportDtoToJSONTyped(json, false);
}

export function AdminPaymentProviderStatusReportDtoToJSONTyped(value?: AdminPaymentProviderStatusReportDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'status': value['status'],
        'count': value['count'],
    };
}

