/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditEventListDto } from './AdminAuditEventListDto';
import {
    AdminAuditEventListDtoFromJSON,
    AdminAuditEventListDtoFromJSONTyped,
    AdminAuditEventListDtoToJSON,
    AdminAuditEventListDtoToJSONTyped,
} from './AdminAuditEventListDto';

/**
 * 
 * @export
 * @interface AdminAuditEventsApiResponseDto
 */
export interface AdminAuditEventsApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEventsApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEventsApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEventsApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {AdminAuditEventListDto}
     * @memberof AdminAuditEventsApiResponseDto
     */
    data: AdminAuditEventListDto | null;
    /**
     * 
     * @type {object}
     * @memberof AdminAuditEventsApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the AdminAuditEventsApiResponseDto interface.
 */
export function instanceOfAdminAuditEventsApiResponseDto(value: object): value is AdminAuditEventsApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AdminAuditEventsApiResponseDtoFromJSON(json: any): AdminAuditEventsApiResponseDto {
    return AdminAuditEventsApiResponseDtoFromJSONTyped(json, false);
}

export function AdminAuditEventsApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditEventsApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': AdminAuditEventListDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function AdminAuditEventsApiResponseDtoToJSON(json: any): AdminAuditEventsApiResponseDto {
    return AdminAuditEventsApiResponseDtoToJSONTyped(json, false);
}

export function AdminAuditEventsApiResponseDtoToJSONTyped(value?: AdminAuditEventsApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminAuditEventListDtoToJSON(value['data']),
        'error': value['error'],
    };
}

