/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizerTournamentRequestDto
 */
export interface CreateOrganizerTournamentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    shortDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    sportId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    cityId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    venueId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    startsAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    endsAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    registrationOpensAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    registrationClosesAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrganizerTournamentRequestDto
     */
    maxParticipants?: number | null;
}

/**
 * Check if a given object implements the CreateOrganizerTournamentRequestDto interface.
 */
export function instanceOfCreateOrganizerTournamentRequestDto(value: object): value is CreateOrganizerTournamentRequestDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sportId' in value) || value['sportId'] === undefined) return false;
    if (!('cityId' in value) || value['cityId'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    return true;
}

export function CreateOrganizerTournamentRequestDtoFromJSON(json: any): CreateOrganizerTournamentRequestDto {
    return CreateOrganizerTournamentRequestDtoFromJSONTyped(json, false);
}

export function CreateOrganizerTournamentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizerTournamentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
        'description': json['description'] == null ? undefined : json['description'],
        'sportId': json['sport_id'],
        'cityId': json['city_id'],
        'venueId': json['venue_id'] == null ? undefined : json['venue_id'],
        'startsAt': json['starts_at'],
        'endsAt': json['ends_at'],
        'registrationOpensAt': json['registration_opens_at'] == null ? undefined : json['registration_opens_at'],
        'registrationClosesAt': json['registration_closes_at'] == null ? undefined : json['registration_closes_at'],
        'maxParticipants': json['max_participants'] == null ? undefined : json['max_participants'],
    };
}

export function CreateOrganizerTournamentRequestDtoToJSON(json: any): CreateOrganizerTournamentRequestDto {
    return CreateOrganizerTournamentRequestDtoToJSONTyped(json, false);
}

export function CreateOrganizerTournamentRequestDtoToJSONTyped(value?: CreateOrganizerTournamentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'short_description': value['shortDescription'],
        'description': value['description'],
        'sport_id': value['sportId'],
        'city_id': value['cityId'],
        'venue_id': value['venueId'],
        'starts_at': value['startsAt'],
        'ends_at': value['endsAt'],
        'registration_opens_at': value['registrationOpensAt'],
        'registration_closes_at': value['registrationClosesAt'],
        'max_participants': value['maxParticipants'],
    };
}

