/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentRefundRequestDto
 */
export interface CreatePaymentRefundRequestDto {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRefundRequestDto
     */
    amount: number;
    /**
     * 
     * @type {CreatePaymentRefundRequestDtoStatusEnum}
     * @memberof CreatePaymentRefundRequestDto
     */
    status?: CreatePaymentRefundRequestDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRefundRequestDto
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRefundRequestDto
     */
    internalNotes?: string;
}


/**
 * @export
 */
export const CreatePaymentRefundRequestDtoStatusEnum = {
    Requested: 'requested',
    ManualRecorded: 'manual_recorded'
} as const;
export type CreatePaymentRefundRequestDtoStatusEnum = typeof CreatePaymentRefundRequestDtoStatusEnum[keyof typeof CreatePaymentRefundRequestDtoStatusEnum];


/**
 * Check if a given object implements the CreatePaymentRefundRequestDto interface.
 */
export function instanceOfCreatePaymentRefundRequestDto(value: object): value is CreatePaymentRefundRequestDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreatePaymentRefundRequestDtoFromJSON(json: any): CreatePaymentRefundRequestDto {
    return CreatePaymentRefundRequestDtoFromJSONTyped(json, false);
}

export function CreatePaymentRefundRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRefundRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
    };
}

export function CreatePaymentRefundRequestDtoToJSON(json: any): CreatePaymentRefundRequestDto {
    return CreatePaymentRefundRequestDtoToJSONTyped(json, false);
}

export function CreatePaymentRefundRequestDtoToJSONTyped(value?: CreatePaymentRefundRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'status': value['status'],
        'reason': value['reason'],
        'internal_notes': value['internalNotes'],
    };
}

