/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTeamMemberRequestDto
 */
export interface CreateTeamMemberRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTeamMemberRequestDto
     */
    participantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamMemberRequestDto
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamMemberRequestDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamMemberRequestDto
     */
    phone?: string;
    /**
     * 
     * @type {CreateTeamMemberRequestDtoRoleEnum}
     * @memberof CreateTeamMemberRequestDto
     */
    role?: CreateTeamMemberRequestDtoRoleEnum;
}


/**
 * @export
 */
export const CreateTeamMemberRequestDtoRoleEnum = {
    Captain: 'CAPTAIN',
    Player: 'PLAYER',
    Substitute: 'SUBSTITUTE'
} as const;
export type CreateTeamMemberRequestDtoRoleEnum = typeof CreateTeamMemberRequestDtoRoleEnum[keyof typeof CreateTeamMemberRequestDtoRoleEnum];


/**
 * Check if a given object implements the CreateTeamMemberRequestDto interface.
 */
export function instanceOfCreateTeamMemberRequestDto(value: object): value is CreateTeamMemberRequestDto {
    return true;
}

export function CreateTeamMemberRequestDtoFromJSON(json: any): CreateTeamMemberRequestDto {
    return CreateTeamMemberRequestDtoFromJSONTyped(json, false);
}

export function CreateTeamMemberRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamMemberRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'participantId': json['participant_id'] == null ? undefined : json['participant_id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function CreateTeamMemberRequestDtoToJSON(json: any): CreateTeamMemberRequestDto {
    return CreateTeamMemberRequestDtoToJSONTyped(json, false);
}

export function CreateTeamMemberRequestDtoToJSONTyped(value?: CreateTeamMemberRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participant_id': value['participantId'],
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'role': value['role'],
    };
}

