/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRegistrationRequestDto
 */
export interface CreateRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateRegistrationRequestDto
     */
    tournamentCategoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegistrationRequestDto
     */
    playerName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegistrationRequestDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegistrationRequestDto
     */
    notes?: string;
}

/**
 * Check if a given object implements the CreateRegistrationRequestDto interface.
 */
export function instanceOfCreateRegistrationRequestDto(value: object): value is CreateRegistrationRequestDto {
    return true;
}

export function CreateRegistrationRequestDtoFromJSON(json: any): CreateRegistrationRequestDto {
    return CreateRegistrationRequestDtoFromJSONTyped(json, false);
}

export function CreateRegistrationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRegistrationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tournamentCategoryId': json['tournament_category_id'] == null ? undefined : json['tournament_category_id'],
        'playerName': json['player_name'] == null ? undefined : json['player_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateRegistrationRequestDtoToJSON(json: any): CreateRegistrationRequestDto {
    return CreateRegistrationRequestDtoToJSONTyped(json, false);
}

export function CreateRegistrationRequestDtoToJSONTyped(value?: CreateRegistrationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tournament_category_id': value['tournamentCategoryId'],
        'player_name': value['playerName'],
        'phone': value['phone'],
        'notes': value['notes'],
    };
}

