/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUserDto } from './CurrentUserDto';
import {
    CurrentUserDtoFromJSON,
    CurrentUserDtoFromJSONTyped,
    CurrentUserDtoToJSON,
    CurrentUserDtoToJSONTyped,
} from './CurrentUserDto';

/**
 * 
 * @export
 * @interface CurrentUserApiResponseDto
 */
export interface CurrentUserApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof CurrentUserApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {CurrentUserDto}
     * @memberof CurrentUserApiResponseDto
     */
    data: CurrentUserDto | null;
    /**
     * 
     * @type {object}
     * @memberof CurrentUserApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the CurrentUserApiResponseDto interface.
 */
export function instanceOfCurrentUserApiResponseDto(value: object): value is CurrentUserApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function CurrentUserApiResponseDtoFromJSON(json: any): CurrentUserApiResponseDto {
    return CurrentUserApiResponseDtoFromJSONTyped(json, false);
}

export function CurrentUserApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': CurrentUserDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function CurrentUserApiResponseDtoToJSON(json: any): CurrentUserApiResponseDto {
    return CurrentUserApiResponseDtoToJSONTyped(json, false);
}

export function CurrentUserApiResponseDtoToJSONTyped(value?: CurrentUserApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': CurrentUserDtoToJSON(value['data']),
        'error': value['error'],
    };
}

