/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FixtureMatchDto } from './FixtureMatchDto';
import {
    FixtureMatchDtoFromJSON,
    FixtureMatchDtoFromJSONTyped,
    FixtureMatchDtoToJSON,
    FixtureMatchDtoToJSONTyped,
} from './FixtureMatchDto';

/**
 * 
 * @export
 * @interface FixtureRoundDto
 */
export interface FixtureRoundDto {
    /**
     * 
     * @type {string}
     * @memberof FixtureRoundDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FixtureRoundDto
     */
    roundNumber: number;
    /**
     * 
     * @type {string}
     * @memberof FixtureRoundDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FixtureRoundDto
     */
    stage: string;
    /**
     * 
     * @type {Array<FixtureMatchDto>}
     * @memberof FixtureRoundDto
     */
    matches: Array<FixtureMatchDto>;
    /**
     * 
     * @type {string}
     * @memberof FixtureRoundDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof FixtureRoundDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the FixtureRoundDto interface.
 */
export function instanceOfFixtureRoundDto(value: object): value is FixtureRoundDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('matches' in value) || value['matches'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function FixtureRoundDtoFromJSON(json: any): FixtureRoundDto {
    return FixtureRoundDtoFromJSONTyped(json, false);
}

export function FixtureRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureRoundDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roundNumber': json['round_number'],
        'name': json['name'],
        'stage': json['stage'],
        'matches': ((json['matches'] as Array<any>).map(FixtureMatchDtoFromJSON)),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function FixtureRoundDtoToJSON(json: any): FixtureRoundDto {
    return FixtureRoundDtoToJSONTyped(json, false);
}

export function FixtureRoundDtoToJSONTyped(value?: FixtureRoundDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'round_number': value['roundNumber'],
        'name': value['name'],
        'stage': value['stage'],
        'matches': ((value['matches'] as Array<any>).map(FixtureMatchDtoToJSON)),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

