/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FixtureSetDto } from './FixtureSetDto';
import {
    FixtureSetDtoFromJSON,
    FixtureSetDtoFromJSONTyped,
    FixtureSetDtoToJSON,
    FixtureSetDtoToJSONTyped,
} from './FixtureSetDto';

/**
 * 
 * @export
 * @interface FixtureSetListApiResponseDto
 */
export interface FixtureSetListApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FixtureSetListApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof FixtureSetListApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof FixtureSetListApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {Array<FixtureSetDto>}
     * @memberof FixtureSetListApiResponseDto
     */
    data: Array<FixtureSetDto> | null;
    /**
     * 
     * @type {object}
     * @memberof FixtureSetListApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the FixtureSetListApiResponseDto interface.
 */
export function instanceOfFixtureSetListApiResponseDto(value: object): value is FixtureSetListApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function FixtureSetListApiResponseDtoFromJSON(json: any): FixtureSetListApiResponseDto {
    return FixtureSetListApiResponseDtoFromJSONTyped(json, false);
}

export function FixtureSetListApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureSetListApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(FixtureSetDtoFromJSON)),
        'error': json['error'],
    };
}

export function FixtureSetListApiResponseDtoToJSON(json: any): FixtureSetListApiResponseDto {
    return FixtureSetListApiResponseDtoToJSONTyped(json, false);
}

export function FixtureSetListApiResponseDtoToJSONTyped(value?: FixtureSetListApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(FixtureSetDtoToJSON)),
        'error': value['error'],
    };
}

