/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FixtureEntrantDto
 */
export interface FixtureEntrantDto {
    /**
     * 
     * @type {string}
     * @memberof FixtureEntrantDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FixtureEntrantDto
     */
    slotNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureEntrantDto
     */
    isBye: boolean;
    /**
     * 
     * @type {string}
     * @memberof FixtureEntrantDto
     */
    participantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FixtureEntrantDto
     */
    teamId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FixtureEntrantDto
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof FixtureEntrantDto
     */
    seed?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FixtureEntrantDto
     */
    score?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof FixtureEntrantDto
     */
    isWinner: boolean;
}

/**
 * Check if a given object implements the FixtureEntrantDto interface.
 */
export function instanceOfFixtureEntrantDto(value: object): value is FixtureEntrantDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slotNumber' in value) || value['slotNumber'] === undefined) return false;
    if (!('isBye' in value) || value['isBye'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('isWinner' in value) || value['isWinner'] === undefined) return false;
    return true;
}

export function FixtureEntrantDtoFromJSON(json: any): FixtureEntrantDto {
    return FixtureEntrantDtoFromJSONTyped(json, false);
}

export function FixtureEntrantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixtureEntrantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slotNumber': json['slot_number'],
        'isBye': json['is_bye'],
        'participantId': json['participant_id'] == null ? undefined : json['participant_id'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'displayName': json['display_name'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'score': json['score'] == null ? undefined : json['score'],
        'isWinner': json['is_winner'],
    };
}

export function FixtureEntrantDtoToJSON(json: any): FixtureEntrantDto {
    return FixtureEntrantDtoToJSONTyped(json, false);
}

export function FixtureEntrantDtoToJSONTyped(value?: FixtureEntrantDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slot_number': value['slotNumber'],
        'is_bye': value['isBye'],
        'participant_id': value['participantId'],
        'team_id': value['teamId'],
        'display_name': value['displayName'],
        'seed': value['seed'],
        'score': value['score'],
        'is_winner': value['isWinner'],
    };
}

