/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthReadyResponseDto } from './HealthReadyResponseDto';
import {
    HealthReadyResponseDtoFromJSON,
    HealthReadyResponseDtoFromJSONTyped,
    HealthReadyResponseDtoToJSON,
    HealthReadyResponseDtoToJSONTyped,
} from './HealthReadyResponseDto';

/**
 * 
 * @export
 * @interface HealthReadyApiResponseDto
 */
export interface HealthReadyApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof HealthReadyApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof HealthReadyApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof HealthReadyApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {HealthReadyResponseDto}
     * @memberof HealthReadyApiResponseDto
     */
    data: HealthReadyResponseDto | null;
    /**
     * 
     * @type {object}
     * @memberof HealthReadyApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the HealthReadyApiResponseDto interface.
 */
export function instanceOfHealthReadyApiResponseDto(value: object): value is HealthReadyApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function HealthReadyApiResponseDtoFromJSON(json: any): HealthReadyApiResponseDto {
    return HealthReadyApiResponseDtoFromJSONTyped(json, false);
}

export function HealthReadyApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthReadyApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': HealthReadyResponseDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function HealthReadyApiResponseDtoToJSON(json: any): HealthReadyApiResponseDto {
    return HealthReadyApiResponseDtoToJSONTyped(json, false);
}

export function HealthReadyApiResponseDtoToJSONTyped(value?: HealthReadyApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': HealthReadyResponseDtoToJSON(value['data']),
        'error': value['error'],
    };
}

