/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthDependencyDto
 */
export interface HealthDependencyDto {
    /**
     * 
     * @type {string}
     * @memberof HealthDependencyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HealthDependencyDto
     */
    status: string;
}

/**
 * Check if a given object implements the HealthDependencyDto interface.
 */
export function instanceOfHealthDependencyDto(value: object): value is HealthDependencyDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthDependencyDtoFromJSON(json: any): HealthDependencyDto {
    return HealthDependencyDtoFromJSONTyped(json, false);
}

export function HealthDependencyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthDependencyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
    };
}

export function HealthDependencyDtoToJSON(json: any): HealthDependencyDto {
    return HealthDependencyDtoToJSONTyped(json, false);
}

export function HealthDependencyDtoToJSONTyped(value?: HealthDependencyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
    };
}

