/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchScoreInputDto
 */
export interface MatchScoreInputDto {
    /**
     * 
     * @type {string}
     * @memberof MatchScoreInputDto
     */
    matchEntrantId: string;
    /**
     * 
     * @type {number}
     * @memberof MatchScoreInputDto
     */
    score: number;
}

/**
 * Check if a given object implements the MatchScoreInputDto interface.
 */
export function instanceOfMatchScoreInputDto(value: object): value is MatchScoreInputDto {
    if (!('matchEntrantId' in value) || value['matchEntrantId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function MatchScoreInputDtoFromJSON(json: any): MatchScoreInputDto {
    return MatchScoreInputDtoFromJSONTyped(json, false);
}

export function MatchScoreInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchScoreInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'matchEntrantId': json['match_entrant_id'],
        'score': json['score'],
    };
}

export function MatchScoreInputDtoToJSON(json: any): MatchScoreInputDto {
    return MatchScoreInputDtoToJSONTyped(json, false);
}

export function MatchScoreInputDtoToJSONTyped(value?: MatchScoreInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_entrant_id': value['matchEntrantId'],
        'score': value['score'],
    };
}

