/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockCompletePaymentRequestDto
 */
export interface MockCompletePaymentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MockCompletePaymentRequestDto
     */
    paymentIntentId: string;
}

/**
 * Check if a given object implements the MockCompletePaymentRequestDto interface.
 */
export function instanceOfMockCompletePaymentRequestDto(value: object): value is MockCompletePaymentRequestDto {
    if (!('paymentIntentId' in value) || value['paymentIntentId'] === undefined) return false;
    return true;
}

export function MockCompletePaymentRequestDtoFromJSON(json: any): MockCompletePaymentRequestDto {
    return MockCompletePaymentRequestDtoFromJSONTyped(json, false);
}

export function MockCompletePaymentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCompletePaymentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntentId': json['payment_intent_id'],
    };
}

export function MockCompletePaymentRequestDtoToJSON(json: any): MockCompletePaymentRequestDto {
    return MockCompletePaymentRequestDtoToJSONTyped(json, false);
}

export function MockCompletePaymentRequestDtoToJSONTyped(value?: MockCompletePaymentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent_id': value['paymentIntentId'],
    };
}

