/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerProfileSummaryDto
 */
export interface OrganizerProfileSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    contactEmail: string;
    /**
     * 
     * @type {object}
     * @memberof OrganizerProfileSummaryDto
     */
    contactPhone?: object | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    verificationStatus: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileSummaryDto
     */
    status: string;
}

/**
 * Check if a given object implements the OrganizerProfileSummaryDto interface.
 */
export function instanceOfOrganizerProfileSummaryDto(value: object): value is OrganizerProfileSummaryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    if (!('verificationStatus' in value) || value['verificationStatus'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrganizerProfileSummaryDtoFromJSON(json: any): OrganizerProfileSummaryDto {
    return OrganizerProfileSummaryDtoFromJSONTyped(json, false);
}

export function OrganizerProfileSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerProfileSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationName': json['organization_name'],
        'slug': json['slug'],
        'contactEmail': json['contact_email'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'verificationStatus': json['verification_status'],
        'status': json['status'],
    };
}

export function OrganizerProfileSummaryDtoToJSON(json: any): OrganizerProfileSummaryDto {
    return OrganizerProfileSummaryDtoToJSONTyped(json, false);
}

export function OrganizerProfileSummaryDtoToJSONTyped(value?: OrganizerProfileSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_name': value['organizationName'],
        'slug': value['slug'],
        'contact_email': value['contactEmail'],
        'contact_phone': value['contactPhone'],
        'verification_status': value['verificationStatus'],
        'status': value['status'],
    };
}

