/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerProfileResponseDto } from './OrganizerProfileResponseDto';
import {
    OrganizerProfileResponseDtoFromJSON,
    OrganizerProfileResponseDtoFromJSONTyped,
    OrganizerProfileResponseDtoToJSON,
    OrganizerProfileResponseDtoToJSONTyped,
} from './OrganizerProfileResponseDto';

/**
 * 
 * @export
 * @interface OrganizerProfileApiResponseDto
 */
export interface OrganizerProfileApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof OrganizerProfileApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {OrganizerProfileResponseDto}
     * @memberof OrganizerProfileApiResponseDto
     */
    data: OrganizerProfileResponseDto | null;
    /**
     * 
     * @type {object}
     * @memberof OrganizerProfileApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the OrganizerProfileApiResponseDto interface.
 */
export function instanceOfOrganizerProfileApiResponseDto(value: object): value is OrganizerProfileApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function OrganizerProfileApiResponseDtoFromJSON(json: any): OrganizerProfileApiResponseDto {
    return OrganizerProfileApiResponseDtoFromJSONTyped(json, false);
}

export function OrganizerProfileApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerProfileApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': OrganizerProfileResponseDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function OrganizerProfileApiResponseDtoToJSON(json: any): OrganizerProfileApiResponseDto {
    return OrganizerProfileApiResponseDtoToJSONTyped(json, false);
}

export function OrganizerProfileApiResponseDtoToJSONTyped(value?: OrganizerProfileApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': OrganizerProfileResponseDtoToJSON(value['data']),
        'error': value['error'],
    };
}

