/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TournamentCategoryDto } from './TournamentCategoryDto';
import {
    TournamentCategoryDtoFromJSON,
    TournamentCategoryDtoFromJSONTyped,
    TournamentCategoryDtoToJSON,
    TournamentCategoryDtoToJSONTyped,
} from './TournamentCategoryDto';
import type { SportDto } from './SportDto';
import {
    SportDtoFromJSON,
    SportDtoFromJSONTyped,
    SportDtoToJSON,
    SportDtoToJSONTyped,
} from './SportDto';
import type { CityDto } from './CityDto';
import {
    CityDtoFromJSON,
    CityDtoFromJSONTyped,
    CityDtoToJSON,
    CityDtoToJSONTyped,
} from './CityDto';
import type { VenueDto } from './VenueDto';
import {
    VenueDtoFromJSON,
    VenueDtoFromJSONTyped,
    VenueDtoToJSON,
    VenueDtoToJSONTyped,
} from './VenueDto';

/**
 * 
 * @export
 * @interface OrganizerTournamentDto
 */
export interface OrganizerTournamentDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    shortDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    description?: string | null;
    /**
     * 
     * @type {SportDto}
     * @memberof OrganizerTournamentDto
     */
    sport: SportDto;
    /**
     * 
     * @type {CityDto}
     * @memberof OrganizerTournamentDto
     */
    city: CityDto;
    /**
     * 
     * @type {VenueDto}
     * @memberof OrganizerTournamentDto
     */
    venue?: VenueDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    startsAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    endsAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    registrationOpensAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    registrationClosesAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentDto
     */
    maxParticipants?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    publishedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    visibility: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentDto
     */
    registrationCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentDto
     */
    pendingRegistrationCount: number;
    /**
     * 
     * @type {Array<TournamentCategoryDto>}
     * @memberof OrganizerTournamentDto
     */
    categories: Array<TournamentCategoryDto>;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTournamentDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerTournamentDto interface.
 */
export function instanceOfOrganizerTournamentDto(value: object): value is OrganizerTournamentDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sport' in value) || value['sport'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('registrationCount' in value) || value['registrationCount'] === undefined) return false;
    if (!('pendingRegistrationCount' in value) || value['pendingRegistrationCount'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerTournamentDtoFromJSON(json: any): OrganizerTournamentDto {
    return OrganizerTournamentDtoFromJSONTyped(json, false);
}

export function OrganizerTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerTournamentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
        'description': json['description'] == null ? undefined : json['description'],
        'sport': SportDtoFromJSON(json['sport']),
        'city': CityDtoFromJSON(json['city']),
        'venue': json['venue'] == null ? undefined : VenueDtoFromJSON(json['venue']),
        'startsAt': json['starts_at'],
        'endsAt': json['ends_at'],
        'registrationOpensAt': json['registration_opens_at'] == null ? undefined : json['registration_opens_at'],
        'registrationClosesAt': json['registration_closes_at'] == null ? undefined : json['registration_closes_at'],
        'maxParticipants': json['max_participants'] == null ? undefined : json['max_participants'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
        'status': json['status'],
        'visibility': json['visibility'],
        'registrationCount': json['registration_count'],
        'pendingRegistrationCount': json['pending_registration_count'],
        'categories': ((json['categories'] as Array<any>).map(TournamentCategoryDtoFromJSON)),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerTournamentDtoToJSON(json: any): OrganizerTournamentDto {
    return OrganizerTournamentDtoToJSONTyped(json, false);
}

export function OrganizerTournamentDtoToJSONTyped(value?: OrganizerTournamentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'short_description': value['shortDescription'],
        'description': value['description'],
        'sport': SportDtoToJSON(value['sport']),
        'city': CityDtoToJSON(value['city']),
        'venue': VenueDtoToJSON(value['venue']),
        'starts_at': value['startsAt'],
        'ends_at': value['endsAt'],
        'registration_opens_at': value['registrationOpensAt'],
        'registration_closes_at': value['registrationClosesAt'],
        'max_participants': value['maxParticipants'],
        'published_at': value['publishedAt'],
        'status': value['status'],
        'visibility': value['visibility'],
        'registration_count': value['registrationCount'],
        'pending_registration_count': value['pendingRegistrationCount'],
        'categories': ((value['categories'] as Array<any>).map(TournamentCategoryDtoToJSON)),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

