/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerRegistrationDto } from './OrganizerRegistrationDto';
import {
    OrganizerRegistrationDtoFromJSON,
    OrganizerRegistrationDtoFromJSONTyped,
    OrganizerRegistrationDtoToJSON,
    OrganizerRegistrationDtoToJSONTyped,
} from './OrganizerRegistrationDto';

/**
 * 
 * @export
 * @interface OrganizerRegistrationApiResponseDto
 */
export interface OrganizerRegistrationApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof OrganizerRegistrationApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {OrganizerRegistrationDto}
     * @memberof OrganizerRegistrationApiResponseDto
     */
    data: OrganizerRegistrationDto | null;
    /**
     * 
     * @type {object}
     * @memberof OrganizerRegistrationApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the OrganizerRegistrationApiResponseDto interface.
 */
export function instanceOfOrganizerRegistrationApiResponseDto(value: object): value is OrganizerRegistrationApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function OrganizerRegistrationApiResponseDtoFromJSON(json: any): OrganizerRegistrationApiResponseDto {
    return OrganizerRegistrationApiResponseDtoFromJSONTyped(json, false);
}

export function OrganizerRegistrationApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerRegistrationApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': OrganizerRegistrationDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function OrganizerRegistrationApiResponseDtoToJSON(json: any): OrganizerRegistrationApiResponseDto {
    return OrganizerRegistrationApiResponseDtoToJSONTyped(json, false);
}

export function OrganizerRegistrationApiResponseDtoToJSONTyped(value?: OrganizerRegistrationApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': OrganizerRegistrationDtoToJSON(value['data']),
        'error': value['error'],
    };
}

