/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerPaymentRefundDto } from './OrganizerPaymentRefundDto';
import {
    OrganizerPaymentRefundDtoFromJSON,
    OrganizerPaymentRefundDtoFromJSONTyped,
    OrganizerPaymentRefundDtoToJSON,
    OrganizerPaymentRefundDtoToJSONTyped,
} from './OrganizerPaymentRefundDto';
import type { OrganizerPaymentAttemptDiagnosticDto } from './OrganizerPaymentAttemptDiagnosticDto';
import {
    OrganizerPaymentAttemptDiagnosticDtoFromJSON,
    OrganizerPaymentAttemptDiagnosticDtoFromJSONTyped,
    OrganizerPaymentAttemptDiagnosticDtoToJSON,
    OrganizerPaymentAttemptDiagnosticDtoToJSONTyped,
} from './OrganizerPaymentAttemptDiagnosticDto';
import type { OrganizerPaymentEventDiagnosticDto } from './OrganizerPaymentEventDiagnosticDto';
import {
    OrganizerPaymentEventDiagnosticDtoFromJSON,
    OrganizerPaymentEventDiagnosticDtoFromJSONTyped,
    OrganizerPaymentEventDiagnosticDtoToJSON,
    OrganizerPaymentEventDiagnosticDtoToJSONTyped,
} from './OrganizerPaymentEventDiagnosticDto';

/**
 * 
 * @export
 * @interface OrganizerPaymentIntentDiagnosticDto
 */
export interface OrganizerPaymentIntentDiagnosticDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    providerIntentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    expiresAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    eventCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    attemptCount: number;
    /**
     * 
     * @type {Array<OrganizerPaymentAttemptDiagnosticDto>}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    attempts: Array<OrganizerPaymentAttemptDiagnosticDto>;
    /**
     * 
     * @type {Array<OrganizerPaymentEventDiagnosticDto>}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    events: Array<OrganizerPaymentEventDiagnosticDto>;
    /**
     * 
     * @type {Array<OrganizerPaymentRefundDto>}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    refunds: Array<OrganizerPaymentRefundDto>;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentIntentDiagnosticDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerPaymentIntentDiagnosticDto interface.
 */
export function instanceOfOrganizerPaymentIntentDiagnosticDto(value: object): value is OrganizerPaymentIntentDiagnosticDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('eventCount' in value) || value['eventCount'] === undefined) return false;
    if (!('attemptCount' in value) || value['attemptCount'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('refunds' in value) || value['refunds'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerPaymentIntentDiagnosticDtoFromJSON(json: any): OrganizerPaymentIntentDiagnosticDto {
    return OrganizerPaymentIntentDiagnosticDtoFromJSONTyped(json, false);
}

export function OrganizerPaymentIntentDiagnosticDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPaymentIntentDiagnosticDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'mode': json['mode'],
        'status': json['status'],
        'amount': json['amount'],
        'currency': json['currency'],
        'providerIntentId': json['provider_intent_id'] == null ? undefined : json['provider_intent_id'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'eventCount': json['event_count'],
        'attemptCount': json['attempt_count'],
        'attempts': ((json['attempts'] as Array<any>).map(OrganizerPaymentAttemptDiagnosticDtoFromJSON)),
        'events': ((json['events'] as Array<any>).map(OrganizerPaymentEventDiagnosticDtoFromJSON)),
        'refunds': ((json['refunds'] as Array<any>).map(OrganizerPaymentRefundDtoFromJSON)),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerPaymentIntentDiagnosticDtoToJSON(json: any): OrganizerPaymentIntentDiagnosticDto {
    return OrganizerPaymentIntentDiagnosticDtoToJSONTyped(json, false);
}

export function OrganizerPaymentIntentDiagnosticDtoToJSONTyped(value?: OrganizerPaymentIntentDiagnosticDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'mode': value['mode'],
        'status': value['status'],
        'amount': value['amount'],
        'currency': value['currency'],
        'provider_intent_id': value['providerIntentId'],
        'expires_at': value['expiresAt'],
        'event_count': value['eventCount'],
        'attempt_count': value['attemptCount'],
        'attempts': ((value['attempts'] as Array<any>).map(OrganizerPaymentAttemptDiagnosticDtoToJSON)),
        'events': ((value['events'] as Array<any>).map(OrganizerPaymentEventDiagnosticDtoToJSON)),
        'refunds': ((value['refunds'] as Array<any>).map(OrganizerPaymentRefundDtoToJSON)),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

