/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerSummaryDto
 */
export interface OrganizerSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerSummaryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerSummaryDto
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerSummaryDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerSummaryDto
     */
    verificationStatus: string;
}

/**
 * Check if a given object implements the OrganizerSummaryDto interface.
 */
export function instanceOfOrganizerSummaryDto(value: object): value is OrganizerSummaryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('verificationStatus' in value) || value['verificationStatus'] === undefined) return false;
    return true;
}

export function OrganizerSummaryDtoFromJSON(json: any): OrganizerSummaryDto {
    return OrganizerSummaryDtoFromJSONTyped(json, false);
}

export function OrganizerSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationName': json['organization_name'],
        'slug': json['slug'],
        'verificationStatus': json['verification_status'],
    };
}

export function OrganizerSummaryDtoToJSON(json: any): OrganizerSummaryDto {
    return OrganizerSummaryDtoToJSONTyped(json, false);
}

export function OrganizerSummaryDtoToJSONTyped(value?: OrganizerSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_name': value['organizationName'],
        'slug': value['slug'],
        'verification_status': value['verificationStatus'],
    };
}

