/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerPaymentRefundDto } from './OrganizerPaymentRefundDto';
import {
    OrganizerPaymentRefundDtoFromJSON,
    OrganizerPaymentRefundDtoFromJSONTyped,
    OrganizerPaymentRefundDtoToJSON,
    OrganizerPaymentRefundDtoToJSONTyped,
} from './OrganizerPaymentRefundDto';
import type { OrganizerRosterUserSummaryDto } from './OrganizerRosterUserSummaryDto';
import {
    OrganizerRosterUserSummaryDtoFromJSON,
    OrganizerRosterUserSummaryDtoFromJSONTyped,
    OrganizerRosterUserSummaryDtoToJSON,
    OrganizerRosterUserSummaryDtoToJSONTyped,
} from './OrganizerRosterUserSummaryDto';
import type { RegistrationCategorySummaryDto } from './RegistrationCategorySummaryDto';
import {
    RegistrationCategorySummaryDtoFromJSON,
    RegistrationCategorySummaryDtoFromJSONTyped,
    RegistrationCategorySummaryDtoToJSON,
    RegistrationCategorySummaryDtoToJSONTyped,
} from './RegistrationCategorySummaryDto';
import type { OrganizerPaymentEventDiagnosticDto } from './OrganizerPaymentEventDiagnosticDto';
import {
    OrganizerPaymentEventDiagnosticDtoFromJSON,
    OrganizerPaymentEventDiagnosticDtoFromJSONTyped,
    OrganizerPaymentEventDiagnosticDtoToJSON,
    OrganizerPaymentEventDiagnosticDtoToJSONTyped,
} from './OrganizerPaymentEventDiagnosticDto';
import type { OrganizerPaymentIntentDiagnosticDto } from './OrganizerPaymentIntentDiagnosticDto';
import {
    OrganizerPaymentIntentDiagnosticDtoFromJSON,
    OrganizerPaymentIntentDiagnosticDtoFromJSONTyped,
    OrganizerPaymentIntentDiagnosticDtoToJSON,
    OrganizerPaymentIntentDiagnosticDtoToJSONTyped,
} from './OrganizerPaymentIntentDiagnosticDto';

/**
 * 
 * @export
 * @interface OrganizerPaymentDetailDto
 */
export interface OrganizerPaymentDetailDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    registrationId: string;
    /**
     * 
     * @type {OrganizerRosterUserSummaryDto}
     * @memberof OrganizerPaymentDetailDto
     */
    user: OrganizerRosterUserSummaryDto;
    /**
     * 
     * @type {RegistrationCategorySummaryDto}
     * @memberof OrganizerPaymentDetailDto
     */
    category?: RegistrationCategorySummaryDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    registrationStatus: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    paymentMode: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    paymentStatus: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentDetailDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    playerEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    reference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    internalNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    paidAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    paymentProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    latestIntentStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    latestIntentProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    latestIntentReference?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentDetailDto
     */
    latestIntentEventCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentDetailDto
     */
    refundCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentDetailDto
     */
    refundedAmount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    latestRefundStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailDto
     */
    updatedAt: string;
    /**
     * 
     * @type {Array<OrganizerPaymentIntentDiagnosticDto>}
     * @memberof OrganizerPaymentDetailDto
     */
    intents: Array<OrganizerPaymentIntentDiagnosticDto>;
    /**
     * 
     * @type {Array<OrganizerPaymentEventDiagnosticDto>}
     * @memberof OrganizerPaymentDetailDto
     */
    events: Array<OrganizerPaymentEventDiagnosticDto>;
    /**
     * 
     * @type {Array<OrganizerPaymentRefundDto>}
     * @memberof OrganizerPaymentDetailDto
     */
    refunds: Array<OrganizerPaymentRefundDto>;
}

/**
 * Check if a given object implements the OrganizerPaymentDetailDto interface.
 */
export function instanceOfOrganizerPaymentDetailDto(value: object): value is OrganizerPaymentDetailDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('registrationId' in value) || value['registrationId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('registrationStatus' in value) || value['registrationStatus'] === undefined) return false;
    if (!('paymentMode' in value) || value['paymentMode'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('latestIntentEventCount' in value) || value['latestIntentEventCount'] === undefined) return false;
    if (!('refundCount' in value) || value['refundCount'] === undefined) return false;
    if (!('refundedAmount' in value) || value['refundedAmount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('intents' in value) || value['intents'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('refunds' in value) || value['refunds'] === undefined) return false;
    return true;
}

export function OrganizerPaymentDetailDtoFromJSON(json: any): OrganizerPaymentDetailDto {
    return OrganizerPaymentDetailDtoFromJSONTyped(json, false);
}

export function OrganizerPaymentDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPaymentDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'registrationId': json['registration_id'],
        'user': OrganizerRosterUserSummaryDtoFromJSON(json['user']),
        'category': json['category'] == null ? undefined : RegistrationCategorySummaryDtoFromJSON(json['category']),
        'registrationStatus': json['registration_status'],
        'paymentMode': json['payment_mode'],
        'paymentStatus': json['payment_status'],
        'amount': json['amount'],
        'currency': json['currency'],
        'playerName': json['player_name'],
        'playerEmail': json['player_email'] == null ? undefined : json['player_email'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'paidAt': json['paid_at'] == null ? undefined : json['paid_at'],
        'paymentProvider': json['payment_provider'] == null ? undefined : json['payment_provider'],
        'latestIntentStatus': json['latest_intent_status'] == null ? undefined : json['latest_intent_status'],
        'latestIntentProvider': json['latest_intent_provider'] == null ? undefined : json['latest_intent_provider'],
        'latestIntentReference': json['latest_intent_reference'] == null ? undefined : json['latest_intent_reference'],
        'latestIntentEventCount': json['latest_intent_event_count'],
        'refundCount': json['refund_count'],
        'refundedAmount': json['refunded_amount'],
        'latestRefundStatus': json['latest_refund_status'] == null ? undefined : json['latest_refund_status'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'intents': ((json['intents'] as Array<any>).map(OrganizerPaymentIntentDiagnosticDtoFromJSON)),
        'events': ((json['events'] as Array<any>).map(OrganizerPaymentEventDiagnosticDtoFromJSON)),
        'refunds': ((json['refunds'] as Array<any>).map(OrganizerPaymentRefundDtoFromJSON)),
    };
}

export function OrganizerPaymentDetailDtoToJSON(json: any): OrganizerPaymentDetailDto {
    return OrganizerPaymentDetailDtoToJSONTyped(json, false);
}

export function OrganizerPaymentDetailDtoToJSONTyped(value?: OrganizerPaymentDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'registration_id': value['registrationId'],
        'user': OrganizerRosterUserSummaryDtoToJSON(value['user']),
        'category': RegistrationCategorySummaryDtoToJSON(value['category']),
        'registration_status': value['registrationStatus'],
        'payment_mode': value['paymentMode'],
        'payment_status': value['paymentStatus'],
        'amount': value['amount'],
        'currency': value['currency'],
        'player_name': value['playerName'],
        'player_email': value['playerEmail'],
        'reference': value['reference'],
        'internal_notes': value['internalNotes'],
        'paid_at': value['paidAt'],
        'payment_provider': value['paymentProvider'],
        'latest_intent_status': value['latestIntentStatus'],
        'latest_intent_provider': value['latestIntentProvider'],
        'latest_intent_reference': value['latestIntentReference'],
        'latest_intent_event_count': value['latestIntentEventCount'],
        'refund_count': value['refundCount'],
        'refunded_amount': value['refundedAmount'],
        'latest_refund_status': value['latestRefundStatus'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'intents': ((value['intents'] as Array<any>).map(OrganizerPaymentIntentDiagnosticDtoToJSON)),
        'events': ((value['events'] as Array<any>).map(OrganizerPaymentEventDiagnosticDtoToJSON)),
        'refunds': ((value['refunds'] as Array<any>).map(OrganizerPaymentRefundDtoToJSON)),
    };
}

