/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerPaymentDetailDto } from './OrganizerPaymentDetailDto';
import {
    OrganizerPaymentDetailDtoFromJSON,
    OrganizerPaymentDetailDtoFromJSONTyped,
    OrganizerPaymentDetailDtoToJSON,
    OrganizerPaymentDetailDtoToJSONTyped,
} from './OrganizerPaymentDetailDto';

/**
 * 
 * @export
 * @interface OrganizerPaymentDetailApiResponseDto
 */
export interface OrganizerPaymentDetailApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentDetailApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentDetailApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {OrganizerPaymentDetailDto}
     * @memberof OrganizerPaymentDetailApiResponseDto
     */
    data: OrganizerPaymentDetailDto | null;
    /**
     * 
     * @type {object}
     * @memberof OrganizerPaymentDetailApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the OrganizerPaymentDetailApiResponseDto interface.
 */
export function instanceOfOrganizerPaymentDetailApiResponseDto(value: object): value is OrganizerPaymentDetailApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function OrganizerPaymentDetailApiResponseDtoFromJSON(json: any): OrganizerPaymentDetailApiResponseDto {
    return OrganizerPaymentDetailApiResponseDtoFromJSONTyped(json, false);
}

export function OrganizerPaymentDetailApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPaymentDetailApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': OrganizerPaymentDetailDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function OrganizerPaymentDetailApiResponseDtoToJSON(json: any): OrganizerPaymentDetailApiResponseDto {
    return OrganizerPaymentDetailApiResponseDtoToJSONTyped(json, false);
}

export function OrganizerPaymentDetailApiResponseDtoToJSONTyped(value?: OrganizerPaymentDetailApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': OrganizerPaymentDetailDtoToJSON(value['data']),
        'error': value['error'],
    };
}

