/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerTournamentDto } from './OrganizerTournamentDto';
import {
    OrganizerTournamentDtoFromJSON,
    OrganizerTournamentDtoFromJSONTyped,
    OrganizerTournamentDtoToJSON,
    OrganizerTournamentDtoToJSONTyped,
} from './OrganizerTournamentDto';

/**
 * 
 * @export
 * @interface OrganizerDashboardDto
 */
export interface OrganizerDashboardDto {
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    totalTournaments: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    draftTournaments: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    publishedTournaments: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    upcomingTournaments: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    totalRegistrations: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerDashboardDto
     */
    pendingRegistrations: number;
    /**
     * 
     * @type {Array<OrganizerTournamentDto>}
     * @memberof OrganizerDashboardDto
     */
    recentTournaments: Array<OrganizerTournamentDto>;
}

/**
 * Check if a given object implements the OrganizerDashboardDto interface.
 */
export function instanceOfOrganizerDashboardDto(value: object): value is OrganizerDashboardDto {
    if (!('totalTournaments' in value) || value['totalTournaments'] === undefined) return false;
    if (!('draftTournaments' in value) || value['draftTournaments'] === undefined) return false;
    if (!('publishedTournaments' in value) || value['publishedTournaments'] === undefined) return false;
    if (!('upcomingTournaments' in value) || value['upcomingTournaments'] === undefined) return false;
    if (!('totalRegistrations' in value) || value['totalRegistrations'] === undefined) return false;
    if (!('pendingRegistrations' in value) || value['pendingRegistrations'] === undefined) return false;
    if (!('recentTournaments' in value) || value['recentTournaments'] === undefined) return false;
    return true;
}

export function OrganizerDashboardDtoFromJSON(json: any): OrganizerDashboardDto {
    return OrganizerDashboardDtoFromJSONTyped(json, false);
}

export function OrganizerDashboardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerDashboardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTournaments': json['total_tournaments'],
        'draftTournaments': json['draft_tournaments'],
        'publishedTournaments': json['published_tournaments'],
        'upcomingTournaments': json['upcoming_tournaments'],
        'totalRegistrations': json['total_registrations'],
        'pendingRegistrations': json['pending_registrations'],
        'recentTournaments': ((json['recent_tournaments'] as Array<any>).map(OrganizerTournamentDtoFromJSON)),
    };
}

export function OrganizerDashboardDtoToJSON(json: any): OrganizerDashboardDto {
    return OrganizerDashboardDtoToJSONTyped(json, false);
}

export function OrganizerDashboardDtoToJSONTyped(value?: OrganizerDashboardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_tournaments': value['totalTournaments'],
        'draft_tournaments': value['draftTournaments'],
        'published_tournaments': value['publishedTournaments'],
        'upcoming_tournaments': value['upcomingTournaments'],
        'total_registrations': value['totalRegistrations'],
        'pending_registrations': value['pendingRegistrations'],
        'recent_tournaments': ((value['recentTournaments'] as Array<any>).map(OrganizerTournamentDtoToJSON)),
    };
}

