/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerTeamDto } from './OrganizerTeamDto';
import {
    OrganizerTeamDtoFromJSON,
    OrganizerTeamDtoFromJSONTyped,
    OrganizerTeamDtoToJSON,
    OrganizerTeamDtoToJSONTyped,
} from './OrganizerTeamDto';

/**
 * 
 * @export
 * @interface OrganizerTeamApiResponseDto
 */
export interface OrganizerTeamApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof OrganizerTeamApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {OrganizerTeamDto}
     * @memberof OrganizerTeamApiResponseDto
     */
    data: OrganizerTeamDto | null;
    /**
     * 
     * @type {object}
     * @memberof OrganizerTeamApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the OrganizerTeamApiResponseDto interface.
 */
export function instanceOfOrganizerTeamApiResponseDto(value: object): value is OrganizerTeamApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function OrganizerTeamApiResponseDtoFromJSON(json: any): OrganizerTeamApiResponseDto {
    return OrganizerTeamApiResponseDtoFromJSONTyped(json, false);
}

export function OrganizerTeamApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerTeamApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': OrganizerTeamDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function OrganizerTeamApiResponseDtoToJSON(json: any): OrganizerTeamApiResponseDto {
    return OrganizerTeamApiResponseDtoToJSONTyped(json, false);
}

export function OrganizerTeamApiResponseDtoToJSONTyped(value?: OrganizerTeamApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': OrganizerTeamDtoToJSON(value['data']),
        'error': value['error'],
    };
}

