/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerRosterUserSummaryDto } from './OrganizerRosterUserSummaryDto';
import {
    OrganizerRosterUserSummaryDtoFromJSON,
    OrganizerRosterUserSummaryDtoFromJSONTyped,
    OrganizerRosterUserSummaryDtoToJSON,
    OrganizerRosterUserSummaryDtoToJSONTyped,
} from './OrganizerRosterUserSummaryDto';
import type { RegistrationCategorySummaryDto } from './RegistrationCategorySummaryDto';
import {
    RegistrationCategorySummaryDtoFromJSON,
    RegistrationCategorySummaryDtoFromJSONTyped,
    RegistrationCategorySummaryDtoToJSON,
    RegistrationCategorySummaryDtoToJSONTyped,
} from './RegistrationCategorySummaryDto';

/**
 * 
 * @export
 * @interface OrganizerRegistrationDto
 */
export interface OrganizerRegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    paymentMode: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    paymentStatus: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizerRegistrationDto
     */
    feeAmount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    feeCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    notes?: string | null;
    /**
     * 
     * @type {OrganizerRosterUserSummaryDto}
     * @memberof OrganizerRegistrationDto
     */
    user: OrganizerRosterUserSummaryDto;
    /**
     * 
     * @type {RegistrationCategorySummaryDto}
     * @memberof OrganizerRegistrationDto
     */
    category?: RegistrationCategorySummaryDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    participantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    registeredAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerRegistrationDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerRegistrationDto interface.
 */
export function instanceOfOrganizerRegistrationDto(value: object): value is OrganizerRegistrationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentMode' in value) || value['paymentMode'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('feeAmount' in value) || value['feeAmount'] === undefined) return false;
    if (!('feeCurrency' in value) || value['feeCurrency'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('registeredAt' in value) || value['registeredAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerRegistrationDtoFromJSON(json: any): OrganizerRegistrationDto {
    return OrganizerRegistrationDtoFromJSONTyped(json, false);
}

export function OrganizerRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerRegistrationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'paymentMode': json['payment_mode'],
        'paymentStatus': json['payment_status'],
        'feeAmount': json['fee_amount'],
        'feeCurrency': json['fee_currency'],
        'playerName': json['player_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'user': OrganizerRosterUserSummaryDtoFromJSON(json['user']),
        'category': json['category'] == null ? undefined : RegistrationCategorySummaryDtoFromJSON(json['category']),
        'participantId': json['participant_id'] == null ? undefined : json['participant_id'],
        'registeredAt': json['registered_at'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerRegistrationDtoToJSON(json: any): OrganizerRegistrationDto {
    return OrganizerRegistrationDtoToJSONTyped(json, false);
}

export function OrganizerRegistrationDtoToJSONTyped(value?: OrganizerRegistrationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'payment_mode': value['paymentMode'],
        'payment_status': value['paymentStatus'],
        'fee_amount': value['feeAmount'],
        'fee_currency': value['feeCurrency'],
        'player_name': value['playerName'],
        'phone': value['phone'],
        'notes': value['notes'],
        'user': OrganizerRosterUserSummaryDtoToJSON(value['user']),
        'category': RegistrationCategorySummaryDtoToJSON(value['category']),
        'participant_id': value['participantId'],
        'registered_at': value['registeredAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

