/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerReportCountDto } from './OrganizerReportCountDto';
import {
    OrganizerReportCountDtoFromJSON,
    OrganizerReportCountDtoFromJSONTyped,
    OrganizerReportCountDtoToJSON,
    OrganizerReportCountDtoToJSONTyped,
} from './OrganizerReportCountDto';

/**
 * 
 * @export
 * @interface OrganizerTournamentReportSummaryDto
 */
export interface OrganizerTournamentReportSummaryDto {
    /**
     * 
     * @type {Array<OrganizerReportCountDto>}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    registrationsByStatus: Array<OrganizerReportCountDto>;
    /**
     * 
     * @type {Array<OrganizerReportCountDto>}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    paymentsByStatus: Array<OrganizerReportCountDto>;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    totalCollectedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    totalRefundedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    participantCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    teamCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    fixtureCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    completedMatchCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentReportSummaryDto
     */
    pendingNotificationCount: number;
}

/**
 * Check if a given object implements the OrganizerTournamentReportSummaryDto interface.
 */
export function instanceOfOrganizerTournamentReportSummaryDto(value: object): value is OrganizerTournamentReportSummaryDto {
    if (!('registrationsByStatus' in value) || value['registrationsByStatus'] === undefined) return false;
    if (!('paymentsByStatus' in value) || value['paymentsByStatus'] === undefined) return false;
    if (!('totalCollectedAmount' in value) || value['totalCollectedAmount'] === undefined) return false;
    if (!('totalRefundedAmount' in value) || value['totalRefundedAmount'] === undefined) return false;
    if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
    if (!('teamCount' in value) || value['teamCount'] === undefined) return false;
    if (!('fixtureCount' in value) || value['fixtureCount'] === undefined) return false;
    if (!('completedMatchCount' in value) || value['completedMatchCount'] === undefined) return false;
    if (!('pendingNotificationCount' in value) || value['pendingNotificationCount'] === undefined) return false;
    return true;
}

export function OrganizerTournamentReportSummaryDtoFromJSON(json: any): OrganizerTournamentReportSummaryDto {
    return OrganizerTournamentReportSummaryDtoFromJSONTyped(json, false);
}

export function OrganizerTournamentReportSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerTournamentReportSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'registrationsByStatus': ((json['registrations_by_status'] as Array<any>).map(OrganizerReportCountDtoFromJSON)),
        'paymentsByStatus': ((json['payments_by_status'] as Array<any>).map(OrganizerReportCountDtoFromJSON)),
        'totalCollectedAmount': json['total_collected_amount'],
        'totalRefundedAmount': json['total_refunded_amount'],
        'participantCount': json['participant_count'],
        'teamCount': json['team_count'],
        'fixtureCount': json['fixture_count'],
        'completedMatchCount': json['completed_match_count'],
        'pendingNotificationCount': json['pending_notification_count'],
    };
}

export function OrganizerTournamentReportSummaryDtoToJSON(json: any): OrganizerTournamentReportSummaryDto {
    return OrganizerTournamentReportSummaryDtoToJSONTyped(json, false);
}

export function OrganizerTournamentReportSummaryDtoToJSONTyped(value?: OrganizerTournamentReportSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'registrations_by_status': ((value['registrationsByStatus'] as Array<any>).map(OrganizerReportCountDtoToJSON)),
        'payments_by_status': ((value['paymentsByStatus'] as Array<any>).map(OrganizerReportCountDtoToJSON)),
        'total_collected_amount': value['totalCollectedAmount'],
        'total_refunded_amount': value['totalRefundedAmount'],
        'participant_count': value['participantCount'],
        'team_count': value['teamCount'],
        'fixture_count': value['fixtureCount'],
        'completed_match_count': value['completedMatchCount'],
        'pending_notification_count': value['pendingNotificationCount'],
    };
}

