/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerTournamentDto } from './OrganizerTournamentDto';
import {
    OrganizerTournamentDtoFromJSON,
    OrganizerTournamentDtoFromJSONTyped,
    OrganizerTournamentDtoToJSON,
    OrganizerTournamentDtoToJSONTyped,
} from './OrganizerTournamentDto';

/**
 * 
 * @export
 * @interface OrganizerTournamentListResponseDto
 */
export interface OrganizerTournamentListResponseDto {
    /**
     * 
     * @type {Array<OrganizerTournamentDto>}
     * @memberof OrganizerTournamentListResponseDto
     */
    items: Array<OrganizerTournamentDto>;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentListResponseDto
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentListResponseDto
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentListResponseDto
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizerTournamentListResponseDto
     */
    totalPages: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizerTournamentListResponseDto
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the OrganizerTournamentListResponseDto interface.
 */
export function instanceOfOrganizerTournamentListResponseDto(value: object): value is OrganizerTournamentListResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function OrganizerTournamentListResponseDtoFromJSON(json: any): OrganizerTournamentListResponseDto {
    return OrganizerTournamentListResponseDtoFromJSONTyped(json, false);
}

export function OrganizerTournamentListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerTournamentListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrganizerTournamentDtoFromJSON)),
        'page': json['page'],
        'limit': json['limit'],
        'total': json['total'],
        'totalPages': json['total_pages'],
        'hasNext': json['has_next'],
    };
}

export function OrganizerTournamentListResponseDtoToJSON(json: any): OrganizerTournamentListResponseDto {
    return OrganizerTournamentListResponseDtoToJSONTyped(json, false);
}

export function OrganizerTournamentListResponseDtoToJSONTyped(value?: OrganizerTournamentListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrganizerTournamentDtoToJSON)),
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'total_pages': value['totalPages'],
        'has_next': value['hasNext'],
    };
}

