/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerProfileResponseDto
 */
export interface OrganizerProfileResponseDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    contactEmail: string;
    /**
     * 
     * @type {object}
     * @memberof OrganizerProfileResponseDto
     */
    contactPhone?: object | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    verificationStatus: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerProfileResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerProfileResponseDto interface.
 */
export function instanceOfOrganizerProfileResponseDto(value: object): value is OrganizerProfileResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    if (!('verificationStatus' in value) || value['verificationStatus'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerProfileResponseDtoFromJSON(json: any): OrganizerProfileResponseDto {
    return OrganizerProfileResponseDtoFromJSONTyped(json, false);
}

export function OrganizerProfileResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerProfileResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationName': json['organization_name'],
        'slug': json['slug'],
        'contactEmail': json['contact_email'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'verificationStatus': json['verification_status'],
        'status': json['status'],
        'userId': json['user_id'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerProfileResponseDtoToJSON(json: any): OrganizerProfileResponseDto {
    return OrganizerProfileResponseDtoToJSONTyped(json, false);
}

export function OrganizerProfileResponseDtoToJSONTyped(value?: OrganizerProfileResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_name': value['organizationName'],
        'slug': value['slug'],
        'contact_email': value['contactEmail'],
        'contact_phone': value['contactPhone'],
        'verification_status': value['verificationStatus'],
        'status': value['status'],
        'user_id': value['userId'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

