/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerTeamMemberDto
 */
export interface OrganizerTeamMemberDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    participantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerTeamMemberDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerTeamMemberDto interface.
 */
export function instanceOfOrganizerTeamMemberDto(value: object): value is OrganizerTeamMemberDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerTeamMemberDtoFromJSON(json: any): OrganizerTeamMemberDto {
    return OrganizerTeamMemberDtoFromJSONTyped(json, false);
}

export function OrganizerTeamMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerTeamMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'participantId': json['participant_id'] == null ? undefined : json['participant_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'displayName': json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'role': json['role'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerTeamMemberDtoToJSON(json: any): OrganizerTeamMemberDto {
    return OrganizerTeamMemberDtoToJSONTyped(json, false);
}

export function OrganizerTeamMemberDtoToJSONTyped(value?: OrganizerTeamMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'participant_id': value['participantId'],
        'user_id': value['userId'],
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'role': value['role'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

