/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerPaymentRefundDto
 */
export interface OrganizerPaymentRefundDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizerPaymentRefundDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    internalNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    providerRefundId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    processedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerPaymentRefundDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerPaymentRefundDto interface.
 */
export function instanceOfOrganizerPaymentRefundDto(value: object): value is OrganizerPaymentRefundDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerPaymentRefundDtoFromJSON(json: any): OrganizerPaymentRefundDto {
    return OrganizerPaymentRefundDtoFromJSONTyped(json, false);
}

export function OrganizerPaymentRefundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPaymentRefundDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'status': json['status'],
        'amount': json['amount'],
        'currency': json['currency'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'providerRefundId': json['provider_refund_id'] == null ? undefined : json['provider_refund_id'],
        'processedAt': json['processed_at'] == null ? undefined : json['processed_at'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerPaymentRefundDtoToJSON(json: any): OrganizerPaymentRefundDto {
    return OrganizerPaymentRefundDtoToJSONTyped(json, false);
}

export function OrganizerPaymentRefundDtoToJSONTyped(value?: OrganizerPaymentRefundDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'status': value['status'],
        'amount': value['amount'],
        'currency': value['currency'],
        'reason': value['reason'],
        'internal_notes': value['internalNotes'],
        'provider_refund_id': value['providerRefundId'],
        'processed_at': value['processedAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

