/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerRosterUserSummaryDto } from './OrganizerRosterUserSummaryDto';
import {
    OrganizerRosterUserSummaryDtoFromJSON,
    OrganizerRosterUserSummaryDtoFromJSONTyped,
    OrganizerRosterUserSummaryDtoToJSON,
    OrganizerRosterUserSummaryDtoToJSONTyped,
} from './OrganizerRosterUserSummaryDto';
import type { RegistrationCategorySummaryDto } from './RegistrationCategorySummaryDto';
import {
    RegistrationCategorySummaryDtoFromJSON,
    RegistrationCategorySummaryDtoFromJSONTyped,
    RegistrationCategorySummaryDtoToJSON,
    RegistrationCategorySummaryDtoToJSONTyped,
} from './RegistrationCategorySummaryDto';

/**
 * 
 * @export
 * @interface OrganizerParticipantDto
 */
export interface OrganizerParticipantDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    tournamentId: string;
    /**
     * 
     * @type {RegistrationCategorySummaryDto}
     * @memberof OrganizerParticipantDto
     */
    category?: RegistrationCategorySummaryDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    registrationId?: string | null;
    /**
     * 
     * @type {OrganizerRosterUserSummaryDto}
     * @memberof OrganizerParticipantDto
     */
    user?: OrganizerRosterUserSummaryDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizerParticipantDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizerParticipantDto interface.
 */
export function instanceOfOrganizerParticipantDto(value: object): value is OrganizerParticipantDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tournamentId' in value) || value['tournamentId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizerParticipantDtoFromJSON(json: any): OrganizerParticipantDto {
    return OrganizerParticipantDtoFromJSONTyped(json, false);
}

export function OrganizerParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerParticipantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tournamentId': json['tournament_id'],
        'category': json['category'] == null ? undefined : RegistrationCategorySummaryDtoFromJSON(json['category']),
        'registrationId': json['registration_id'] == null ? undefined : json['registration_id'],
        'user': json['user'] == null ? undefined : OrganizerRosterUserSummaryDtoFromJSON(json['user']),
        'displayName': json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'source': json['source'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizerParticipantDtoToJSON(json: any): OrganizerParticipantDto {
    return OrganizerParticipantDtoToJSONTyped(json, false);
}

export function OrganizerParticipantDtoToJSONTyped(value?: OrganizerParticipantDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tournament_id': value['tournamentId'],
        'category': RegistrationCategorySummaryDtoToJSON(value['category']),
        'registration_id': value['registrationId'],
        'user': OrganizerRosterUserSummaryDtoToJSON(value['user']),
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'source': value['source'],
        'status': value['status'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

