/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TournamentCategoryDto } from './TournamentCategoryDto';
import {
    TournamentCategoryDtoFromJSON,
    TournamentCategoryDtoFromJSONTyped,
    TournamentCategoryDtoToJSON,
    TournamentCategoryDtoToJSONTyped,
} from './TournamentCategoryDto';
import type { PublicFixtureStandingDto } from './PublicFixtureStandingDto';
import {
    PublicFixtureStandingDtoFromJSON,
    PublicFixtureStandingDtoFromJSONTyped,
    PublicFixtureStandingDtoToJSON,
    PublicFixtureStandingDtoToJSONTyped,
} from './PublicFixtureStandingDto';
import type { PublicFixtureRoundDto } from './PublicFixtureRoundDto';
import {
    PublicFixtureRoundDtoFromJSON,
    PublicFixtureRoundDtoFromJSONTyped,
    PublicFixtureRoundDtoToJSON,
    PublicFixtureRoundDtoToJSONTyped,
} from './PublicFixtureRoundDto';

/**
 * 
 * @export
 * @interface PublicFixtureSetDto
 */
export interface PublicFixtureSetDto {
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    id: string;
    /**
     * 
     * @type {TournamentCategoryDto}
     * @memberof PublicFixtureSetDto
     */
    category: TournamentCategoryDto;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    format: string;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    entrantType: string;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureSetDto
     */
    matchCount: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureSetDto
     */
    completedMatchCount: number;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureSetDto
     */
    publishedAt?: string | null;
    /**
     * 
     * @type {Array<PublicFixtureRoundDto>}
     * @memberof PublicFixtureSetDto
     */
    rounds: Array<PublicFixtureRoundDto>;
    /**
     * 
     * @type {Array<PublicFixtureStandingDto>}
     * @memberof PublicFixtureSetDto
     */
    standings: Array<PublicFixtureStandingDto>;
}

/**
 * Check if a given object implements the PublicFixtureSetDto interface.
 */
export function instanceOfPublicFixtureSetDto(value: object): value is PublicFixtureSetDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('entrantType' in value) || value['entrantType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('matchCount' in value) || value['matchCount'] === undefined) return false;
    if (!('completedMatchCount' in value) || value['completedMatchCount'] === undefined) return false;
    if (!('rounds' in value) || value['rounds'] === undefined) return false;
    if (!('standings' in value) || value['standings'] === undefined) return false;
    return true;
}

export function PublicFixtureSetDtoFromJSON(json: any): PublicFixtureSetDto {
    return PublicFixtureSetDtoFromJSONTyped(json, false);
}

export function PublicFixtureSetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFixtureSetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': TournamentCategoryDtoFromJSON(json['category']),
        'format': json['format'],
        'entrantType': json['entrant_type'],
        'status': json['status'],
        'name': json['name'] == null ? undefined : json['name'],
        'matchCount': json['match_count'],
        'completedMatchCount': json['completed_match_count'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
        'rounds': ((json['rounds'] as Array<any>).map(PublicFixtureRoundDtoFromJSON)),
        'standings': ((json['standings'] as Array<any>).map(PublicFixtureStandingDtoFromJSON)),
    };
}

export function PublicFixtureSetDtoToJSON(json: any): PublicFixtureSetDto {
    return PublicFixtureSetDtoToJSONTyped(json, false);
}

export function PublicFixtureSetDtoToJSONTyped(value?: PublicFixtureSetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': TournamentCategoryDtoToJSON(value['category']),
        'format': value['format'],
        'entrant_type': value['entrantType'],
        'status': value['status'],
        'name': value['name'],
        'match_count': value['matchCount'],
        'completed_match_count': value['completedMatchCount'],
        'published_at': value['publishedAt'],
        'rounds': ((value['rounds'] as Array<any>).map(PublicFixtureRoundDtoToJSON)),
        'standings': ((value['standings'] as Array<any>).map(PublicFixtureStandingDtoToJSON)),
    };
}

