/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicFixtureMatchDto } from './PublicFixtureMatchDto';
import {
    PublicFixtureMatchDtoFromJSON,
    PublicFixtureMatchDtoFromJSONTyped,
    PublicFixtureMatchDtoToJSON,
    PublicFixtureMatchDtoToJSONTyped,
} from './PublicFixtureMatchDto';

/**
 * 
 * @export
 * @interface PublicFixtureRoundDto
 */
export interface PublicFixtureRoundDto {
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureRoundDto
     */
    roundNumber: number;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureRoundDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureRoundDto
     */
    stage: string;
    /**
     * 
     * @type {Array<PublicFixtureMatchDto>}
     * @memberof PublicFixtureRoundDto
     */
    matches: Array<PublicFixtureMatchDto>;
}

/**
 * Check if a given object implements the PublicFixtureRoundDto interface.
 */
export function instanceOfPublicFixtureRoundDto(value: object): value is PublicFixtureRoundDto {
    if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('matches' in value) || value['matches'] === undefined) return false;
    return true;
}

export function PublicFixtureRoundDtoFromJSON(json: any): PublicFixtureRoundDto {
    return PublicFixtureRoundDtoFromJSONTyped(json, false);
}

export function PublicFixtureRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFixtureRoundDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roundNumber': json['round_number'],
        'name': json['name'],
        'stage': json['stage'],
        'matches': ((json['matches'] as Array<any>).map(PublicFixtureMatchDtoFromJSON)),
    };
}

export function PublicFixtureRoundDtoToJSON(json: any): PublicFixtureRoundDto {
    return PublicFixtureRoundDtoToJSONTyped(json, false);
}

export function PublicFixtureRoundDtoToJSONTyped(value?: PublicFixtureRoundDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round_number': value['roundNumber'],
        'name': value['name'],
        'stage': value['stage'],
        'matches': ((value['matches'] as Array<any>).map(PublicFixtureMatchDtoToJSON)),
    };
}

