/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicFixtureEntrantDto } from './PublicFixtureEntrantDto';
import {
    PublicFixtureEntrantDtoFromJSON,
    PublicFixtureEntrantDtoFromJSONTyped,
    PublicFixtureEntrantDtoToJSON,
    PublicFixtureEntrantDtoToJSONTyped,
} from './PublicFixtureEntrantDto';

/**
 * 
 * @export
 * @interface PublicFixtureMatchDto
 */
export interface PublicFixtureMatchDto {
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureMatchDto
     */
    matchNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureMatchDto
     */
    roundPosition: number;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    scheduledAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    venueName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    courtName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicFixtureMatchDto
     */
    completedAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PublicFixtureMatchDto
     */
    winnerSlotNumber?: number | null;
    /**
     * 
     * @type {Array<PublicFixtureEntrantDto>}
     * @memberof PublicFixtureMatchDto
     */
    entrants: Array<PublicFixtureEntrantDto>;
}

/**
 * Check if a given object implements the PublicFixtureMatchDto interface.
 */
export function instanceOfPublicFixtureMatchDto(value: object): value is PublicFixtureMatchDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('matchNumber' in value) || value['matchNumber'] === undefined) return false;
    if (!('roundPosition' in value) || value['roundPosition'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('entrants' in value) || value['entrants'] === undefined) return false;
    return true;
}

export function PublicFixtureMatchDtoFromJSON(json: any): PublicFixtureMatchDto {
    return PublicFixtureMatchDtoFromJSONTyped(json, false);
}

export function PublicFixtureMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFixtureMatchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'matchNumber': json['match_number'],
        'roundPosition': json['round_position'],
        'status': json['status'],
        'scheduledAt': json['scheduled_at'] == null ? undefined : json['scheduled_at'],
        'venueName': json['venue_name'] == null ? undefined : json['venue_name'],
        'courtName': json['court_name'] == null ? undefined : json['court_name'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'winnerSlotNumber': json['winner_slot_number'] == null ? undefined : json['winner_slot_number'],
        'entrants': ((json['entrants'] as Array<any>).map(PublicFixtureEntrantDtoFromJSON)),
    };
}

export function PublicFixtureMatchDtoToJSON(json: any): PublicFixtureMatchDto {
    return PublicFixtureMatchDtoToJSONTyped(json, false);
}

export function PublicFixtureMatchDtoToJSONTyped(value?: PublicFixtureMatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'match_number': value['matchNumber'],
        'round_position': value['roundPosition'],
        'status': value['status'],
        'scheduled_at': value['scheduledAt'],
        'venue_name': value['venueName'],
        'court_name': value['courtName'],
        'completed_at': value['completedAt'],
        'winner_slot_number': value['winnerSlotNumber'],
        'entrants': ((value['entrants'] as Array<any>).map(PublicFixtureEntrantDtoToJSON)),
    };
}

