/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerSummaryDto } from './OrganizerSummaryDto';
import {
    OrganizerSummaryDtoFromJSON,
    OrganizerSummaryDtoFromJSONTyped,
    OrganizerSummaryDtoToJSON,
    OrganizerSummaryDtoToJSONTyped,
} from './OrganizerSummaryDto';
import type { SportDto } from './SportDto';
import {
    SportDtoFromJSON,
    SportDtoFromJSONTyped,
    SportDtoToJSON,
    SportDtoToJSONTyped,
} from './SportDto';
import type { CityDto } from './CityDto';
import {
    CityDtoFromJSON,
    CityDtoFromJSONTyped,
    CityDtoToJSON,
    CityDtoToJSONTyped,
} from './CityDto';
import type { VenueDto } from './VenueDto';
import {
    VenueDtoFromJSON,
    VenueDtoFromJSONTyped,
    VenueDtoToJSON,
    VenueDtoToJSONTyped,
} from './VenueDto';

/**
 * 
 * @export
 * @interface RegistrationTournamentSummaryDto
 */
export interface RegistrationTournamentSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof RegistrationTournamentSummaryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTournamentSummaryDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTournamentSummaryDto
     */
    title: string;
    /**
     * 
     * @type {SportDto}
     * @memberof RegistrationTournamentSummaryDto
     */
    sport: SportDto;
    /**
     * 
     * @type {CityDto}
     * @memberof RegistrationTournamentSummaryDto
     */
    city: CityDto;
    /**
     * 
     * @type {VenueDto}
     * @memberof RegistrationTournamentSummaryDto
     */
    venue?: VenueDto | null;
    /**
     * 
     * @type {OrganizerSummaryDto}
     * @memberof RegistrationTournamentSummaryDto
     */
    organizer: OrganizerSummaryDto;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTournamentSummaryDto
     */
    startsAt: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTournamentSummaryDto
     */
    endsAt: string;
}

/**
 * Check if a given object implements the RegistrationTournamentSummaryDto interface.
 */
export function instanceOfRegistrationTournamentSummaryDto(value: object): value is RegistrationTournamentSummaryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sport' in value) || value['sport'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('organizer' in value) || value['organizer'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    return true;
}

export function RegistrationTournamentSummaryDtoFromJSON(json: any): RegistrationTournamentSummaryDto {
    return RegistrationTournamentSummaryDtoFromJSONTyped(json, false);
}

export function RegistrationTournamentSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationTournamentSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'sport': SportDtoFromJSON(json['sport']),
        'city': CityDtoFromJSON(json['city']),
        'venue': json['venue'] == null ? undefined : VenueDtoFromJSON(json['venue']),
        'organizer': OrganizerSummaryDtoFromJSON(json['organizer']),
        'startsAt': json['starts_at'],
        'endsAt': json['ends_at'],
    };
}

export function RegistrationTournamentSummaryDtoToJSON(json: any): RegistrationTournamentSummaryDto {
    return RegistrationTournamentSummaryDtoToJSONTyped(json, false);
}

export function RegistrationTournamentSummaryDtoToJSONTyped(value?: RegistrationTournamentSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'sport': SportDtoToJSON(value['sport']),
        'city': CityDtoToJSON(value['city']),
        'venue': VenueDtoToJSON(value['venue']),
        'organizer': OrganizerSummaryDtoToJSON(value['organizer']),
        'starts_at': value['startsAt'],
        'ends_at': value['endsAt'],
    };
}

