/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistrationDto } from './RegistrationDto';
import {
    RegistrationDtoFromJSON,
    RegistrationDtoFromJSONTyped,
    RegistrationDtoToJSON,
    RegistrationDtoToJSONTyped,
} from './RegistrationDto';

/**
 * 
 * @export
 * @interface RegistrationApiResponseDto
 */
export interface RegistrationApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof RegistrationApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof RegistrationApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {RegistrationDto}
     * @memberof RegistrationApiResponseDto
     */
    data: RegistrationDto | null;
    /**
     * 
     * @type {object}
     * @memberof RegistrationApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the RegistrationApiResponseDto interface.
 */
export function instanceOfRegistrationApiResponseDto(value: object): value is RegistrationApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function RegistrationApiResponseDtoFromJSON(json: any): RegistrationApiResponseDto {
    return RegistrationApiResponseDtoFromJSONTyped(json, false);
}

export function RegistrationApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': RegistrationDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function RegistrationApiResponseDtoToJSON(json: any): RegistrationApiResponseDto {
    return RegistrationApiResponseDtoToJSONTyped(json, false);
}

export function RegistrationApiResponseDtoToJSONTyped(value?: RegistrationApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': RegistrationDtoToJSON(value['data']),
        'error': value['error'],
    };
}

