/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistrationPaymentSummaryDto } from './RegistrationPaymentSummaryDto';
import {
    RegistrationPaymentSummaryDtoFromJSON,
    RegistrationPaymentSummaryDtoFromJSONTyped,
    RegistrationPaymentSummaryDtoToJSON,
    RegistrationPaymentSummaryDtoToJSONTyped,
} from './RegistrationPaymentSummaryDto';
import type { RegistrationCategorySummaryDto } from './RegistrationCategorySummaryDto';
import {
    RegistrationCategorySummaryDtoFromJSON,
    RegistrationCategorySummaryDtoFromJSONTyped,
    RegistrationCategorySummaryDtoToJSON,
    RegistrationCategorySummaryDtoToJSONTyped,
} from './RegistrationCategorySummaryDto';
import type { RegistrationTournamentSummaryDto } from './RegistrationTournamentSummaryDto';
import {
    RegistrationTournamentSummaryDtoFromJSON,
    RegistrationTournamentSummaryDtoFromJSONTyped,
    RegistrationTournamentSummaryDtoToJSON,
    RegistrationTournamentSummaryDtoToJSONTyped,
} from './RegistrationTournamentSummaryDto';

/**
 * 
 * @export
 * @interface RegistrationDto
 */
export interface RegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    paymentMode: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    paymentStatus: string;
    /**
     * 
     * @type {number}
     * @memberof RegistrationDto
     */
    feeAmount: number;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    feeCurrency: string;
    /**
     * 
     * @type {RegistrationPaymentSummaryDto}
     * @memberof RegistrationDto
     */
    payment: RegistrationPaymentSummaryDto;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    registeredAt: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    cancelledAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDto
     */
    updatedAt: string;
    /**
     * 
     * @type {RegistrationTournamentSummaryDto}
     * @memberof RegistrationDto
     */
    tournament: RegistrationTournamentSummaryDto;
    /**
     * 
     * @type {RegistrationCategorySummaryDto}
     * @memberof RegistrationDto
     */
    category?: RegistrationCategorySummaryDto | null;
}

/**
 * Check if a given object implements the RegistrationDto interface.
 */
export function instanceOfRegistrationDto(value: object): value is RegistrationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentMode' in value) || value['paymentMode'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('feeAmount' in value) || value['feeAmount'] === undefined) return false;
    if (!('feeCurrency' in value) || value['feeCurrency'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('registeredAt' in value) || value['registeredAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('tournament' in value) || value['tournament'] === undefined) return false;
    return true;
}

export function RegistrationDtoFromJSON(json: any): RegistrationDto {
    return RegistrationDtoFromJSONTyped(json, false);
}

export function RegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'paymentMode': json['payment_mode'],
        'paymentStatus': json['payment_status'],
        'feeAmount': json['fee_amount'],
        'feeCurrency': json['fee_currency'],
        'payment': RegistrationPaymentSummaryDtoFromJSON(json['payment']),
        'playerName': json['player_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'registeredAt': json['registered_at'],
        'cancelledAt': json['cancelled_at'] == null ? undefined : json['cancelled_at'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'tournament': RegistrationTournamentSummaryDtoFromJSON(json['tournament']),
        'category': json['category'] == null ? undefined : RegistrationCategorySummaryDtoFromJSON(json['category']),
    };
}

export function RegistrationDtoToJSON(json: any): RegistrationDto {
    return RegistrationDtoToJSONTyped(json, false);
}

export function RegistrationDtoToJSONTyped(value?: RegistrationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'payment_mode': value['paymentMode'],
        'payment_status': value['paymentStatus'],
        'fee_amount': value['feeAmount'],
        'fee_currency': value['feeCurrency'],
        'payment': RegistrationPaymentSummaryDtoToJSON(value['payment']),
        'player_name': value['playerName'],
        'phone': value['phone'],
        'notes': value['notes'],
        'registered_at': value['registeredAt'],
        'cancelled_at': value['cancelledAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'tournament': RegistrationTournamentSummaryDtoToJSON(value['tournament']),
        'category': RegistrationCategorySummaryDtoToJSON(value['category']),
    };
}

