/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationPaymentSummaryDto
 */
export interface RegistrationPaymentSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof RegistrationPaymentSummaryDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    offlineInstructions?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    paidAt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationPaymentSummaryDto
     */
    onlinePaymentAvailable: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    latestIntentStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    latestIntentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    checkoutUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationPaymentSummaryDto
     */
    eventCount: number;
    /**
     * 
     * @type {number}
     * @memberof RegistrationPaymentSummaryDto
     */
    refundCount: number;
    /**
     * 
     * @type {number}
     * @memberof RegistrationPaymentSummaryDto
     */
    refundedAmount: number;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    latestRefundStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPaymentSummaryDto
     */
    latestRefundProcessedAt?: string | null;
}

/**
 * Check if a given object implements the RegistrationPaymentSummaryDto interface.
 */
export function instanceOfRegistrationPaymentSummaryDto(value: object): value is RegistrationPaymentSummaryDto {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('onlinePaymentAvailable' in value) || value['onlinePaymentAvailable'] === undefined) return false;
    if (!('eventCount' in value) || value['eventCount'] === undefined) return false;
    if (!('refundCount' in value) || value['refundCount'] === undefined) return false;
    if (!('refundedAmount' in value) || value['refundedAmount'] === undefined) return false;
    return true;
}

export function RegistrationPaymentSummaryDtoFromJSON(json: any): RegistrationPaymentSummaryDto {
    return RegistrationPaymentSummaryDtoFromJSONTyped(json, false);
}

export function RegistrationPaymentSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationPaymentSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'status': json['status'],
        'amount': json['amount'],
        'currency': json['currency'],
        'offlineInstructions': json['offline_instructions'] == null ? undefined : json['offline_instructions'],
        'paidAt': json['paid_at'] == null ? undefined : json['paid_at'],
        'onlinePaymentAvailable': json['online_payment_available'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'latestIntentStatus': json['latest_intent_status'] == null ? undefined : json['latest_intent_status'],
        'latestIntentId': json['latest_intent_id'] == null ? undefined : json['latest_intent_id'],
        'checkoutUrl': json['checkout_url'] == null ? undefined : json['checkout_url'],
        'eventCount': json['event_count'],
        'refundCount': json['refund_count'],
        'refundedAmount': json['refunded_amount'],
        'latestRefundStatus': json['latest_refund_status'] == null ? undefined : json['latest_refund_status'],
        'latestRefundProcessedAt': json['latest_refund_processed_at'] == null ? undefined : json['latest_refund_processed_at'],
    };
}

export function RegistrationPaymentSummaryDtoToJSON(json: any): RegistrationPaymentSummaryDto {
    return RegistrationPaymentSummaryDtoToJSONTyped(json, false);
}

export function RegistrationPaymentSummaryDtoToJSONTyped(value?: RegistrationPaymentSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'status': value['status'],
        'amount': value['amount'],
        'currency': value['currency'],
        'offline_instructions': value['offlineInstructions'],
        'paid_at': value['paidAt'],
        'online_payment_available': value['onlinePaymentAvailable'],
        'provider': value['provider'],
        'latest_intent_status': value['latestIntentStatus'],
        'latest_intent_id': value['latestIntentId'],
        'checkout_url': value['checkoutUrl'],
        'event_count': value['eventCount'],
        'refund_count': value['refundCount'],
        'refunded_amount': value['refundedAmount'],
        'latest_refund_status': value['latestRefundStatus'],
        'latest_refund_processed_at': value['latestRefundProcessedAt'],
    };
}

