/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectRegistrationRequestDto
 */
export interface RejectRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RejectRegistrationRequestDto
     */
    reason?: string;
}

/**
 * Check if a given object implements the RejectRegistrationRequestDto interface.
 */
export function instanceOfRejectRegistrationRequestDto(value: object): value is RejectRegistrationRequestDto {
    return true;
}

export function RejectRegistrationRequestDtoFromJSON(json: any): RejectRegistrationRequestDto {
    return RejectRegistrationRequestDtoFromJSONTyped(json, false);
}

export function RejectRegistrationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectRegistrationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RejectRegistrationRequestDtoToJSON(json: any): RejectRegistrationRequestDto {
    return RejectRegistrationRequestDtoToJSONTyped(json, false);
}

export function RejectRegistrationRequestDtoToJSONTyped(value?: RejectRegistrationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

