/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoundRobinStandingDto
 */
export interface RoundRobinStandingDto {
    /**
     * 
     * @type {string}
     * @memberof RoundRobinStandingDto
     */
    entrantId: string;
    /**
     * 
     * @type {string}
     * @memberof RoundRobinStandingDto
     */
    entrantType: string;
    /**
     * 
     * @type {string}
     * @memberof RoundRobinStandingDto
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    played: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    draws: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    points: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    scoreFor: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    scoreAgainst: number;
    /**
     * 
     * @type {number}
     * @memberof RoundRobinStandingDto
     */
    scoreDifference: number;
}

/**
 * Check if a given object implements the RoundRobinStandingDto interface.
 */
export function instanceOfRoundRobinStandingDto(value: object): value is RoundRobinStandingDto {
    if (!('entrantId' in value) || value['entrantId'] === undefined) return false;
    if (!('entrantType' in value) || value['entrantType'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('played' in value) || value['played'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('draws' in value) || value['draws'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('scoreFor' in value) || value['scoreFor'] === undefined) return false;
    if (!('scoreAgainst' in value) || value['scoreAgainst'] === undefined) return false;
    if (!('scoreDifference' in value) || value['scoreDifference'] === undefined) return false;
    return true;
}

export function RoundRobinStandingDtoFromJSON(json: any): RoundRobinStandingDto {
    return RoundRobinStandingDtoFromJSONTyped(json, false);
}

export function RoundRobinStandingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoundRobinStandingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'entrantId': json['entrant_id'],
        'entrantType': json['entrant_type'],
        'displayName': json['display_name'],
        'played': json['played'],
        'wins': json['wins'],
        'draws': json['draws'],
        'losses': json['losses'],
        'points': json['points'],
        'scoreFor': json['score_for'],
        'scoreAgainst': json['score_against'],
        'scoreDifference': json['score_difference'],
    };
}

export function RoundRobinStandingDtoToJSON(json: any): RoundRobinStandingDto {
    return RoundRobinStandingDtoToJSONTyped(json, false);
}

export function RoundRobinStandingDtoToJSONTyped(value?: RoundRobinStandingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entrant_id': value['entrantId'],
        'entrant_type': value['entrantType'],
        'display_name': value['displayName'],
        'played': value['played'],
        'wins': value['wins'],
        'draws': value['draws'],
        'losses': value['losses'],
        'points': value['points'],
        'score_for': value['scoreFor'],
        'score_against': value['scoreAgainst'],
        'score_difference': value['scoreDifference'],
    };
}

