/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequestDto
 */
export interface SignupRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    displayName: string;
    /**
     * 
     * @type {SignupRequestDtoRoleEnum}
     * @memberof SignupRequestDto
     */
    role: SignupRequestDtoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    organizationName?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    contactPhone?: string;
}


/**
 * @export
 */
export const SignupRequestDtoRoleEnum = {
    Player: 'player',
    Organizer: 'organizer'
} as const;
export type SignupRequestDtoRoleEnum = typeof SignupRequestDtoRoleEnum[keyof typeof SignupRequestDtoRoleEnum];


/**
 * Check if a given object implements the SignupRequestDto interface.
 */
export function instanceOfSignupRequestDto(value: object): value is SignupRequestDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function SignupRequestDtoFromJSON(json: any): SignupRequestDto {
    return SignupRequestDtoFromJSONTyped(json, false);
}

export function SignupRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'displayName': json['display_name'],
        'role': json['role'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
    };
}

export function SignupRequestDtoToJSON(json: any): SignupRequestDto {
    return SignupRequestDtoToJSONTyped(json, false);
}

export function SignupRequestDtoToJSONTyped(value?: SignupRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'display_name': value['displayName'],
        'role': value['role'],
        'organization_name': value['organizationName'],
        'contact_phone': value['contactPhone'],
    };
}

