/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkipNotificationRequestDto
 */
export interface SkipNotificationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SkipNotificationRequestDto
     */
    reason?: string;
}

/**
 * Check if a given object implements the SkipNotificationRequestDto interface.
 */
export function instanceOfSkipNotificationRequestDto(value: object): value is SkipNotificationRequestDto {
    return true;
}

export function SkipNotificationRequestDtoFromJSON(json: any): SkipNotificationRequestDto {
    return SkipNotificationRequestDtoFromJSONTyped(json, false);
}

export function SkipNotificationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkipNotificationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function SkipNotificationRequestDtoToJSON(json: any): SkipNotificationRequestDto {
    return SkipNotificationRequestDtoToJSONTyped(json, false);
}

export function SkipNotificationRequestDtoToJSONTyped(value?: SkipNotificationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

