/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentCategoryDto
 */
export interface TournamentCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    formatType: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    participantType: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    genderType: string;
    /**
     * 
     * @type {number}
     * @memberof TournamentCategoryDto
     */
    minAge?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TournamentCategoryDto
     */
    maxAge?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TournamentCategoryDto
     */
    entryFeeAmount: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    entryFeeCurrency: string;
    /**
     * 
     * @type {number}
     * @memberof TournamentCategoryDto
     */
    capacity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TournamentCategoryDto
     */
    status: string;
}

/**
 * Check if a given object implements the TournamentCategoryDto interface.
 */
export function instanceOfTournamentCategoryDto(value: object): value is TournamentCategoryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('formatType' in value) || value['formatType'] === undefined) return false;
    if (!('participantType' in value) || value['participantType'] === undefined) return false;
    if (!('genderType' in value) || value['genderType'] === undefined) return false;
    if (!('entryFeeAmount' in value) || value['entryFeeAmount'] === undefined) return false;
    if (!('entryFeeCurrency' in value) || value['entryFeeCurrency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TournamentCategoryDtoFromJSON(json: any): TournamentCategoryDto {
    return TournamentCategoryDtoFromJSONTyped(json, false);
}

export function TournamentCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'formatType': json['format_type'],
        'participantType': json['participant_type'],
        'genderType': json['gender_type'],
        'minAge': json['min_age'] == null ? undefined : json['min_age'],
        'maxAge': json['max_age'] == null ? undefined : json['max_age'],
        'entryFeeAmount': json['entry_fee_amount'],
        'entryFeeCurrency': json['entry_fee_currency'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'status': json['status'],
    };
}

export function TournamentCategoryDtoToJSON(json: any): TournamentCategoryDto {
    return TournamentCategoryDtoToJSONTyped(json, false);
}

export function TournamentCategoryDtoToJSONTyped(value?: TournamentCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'format_type': value['formatType'],
        'participant_type': value['participantType'],
        'gender_type': value['genderType'],
        'min_age': value['minAge'],
        'max_age': value['maxAge'],
        'entry_fee_amount': value['entryFeeAmount'],
        'entry_fee_currency': value['entryFeeCurrency'],
        'capacity': value['capacity'],
        'status': value['status'],
    };
}

