/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TournamentListItemDto } from './TournamentListItemDto';
import {
    TournamentListItemDtoFromJSON,
    TournamentListItemDtoFromJSONTyped,
    TournamentListItemDtoToJSON,
    TournamentListItemDtoToJSONTyped,
} from './TournamentListItemDto';
import type { PaginationDto } from './PaginationDto';
import {
    PaginationDtoFromJSON,
    PaginationDtoFromJSONTyped,
    PaginationDtoToJSON,
    PaginationDtoToJSONTyped,
} from './PaginationDto';

/**
 * 
 * @export
 * @interface TournamentListResponseDto
 */
export interface TournamentListResponseDto {
    /**
     * 
     * @type {Array<TournamentListItemDto>}
     * @memberof TournamentListResponseDto
     */
    items: Array<TournamentListItemDto>;
    /**
     * 
     * @type {PaginationDto}
     * @memberof TournamentListResponseDto
     */
    pagination: PaginationDto;
}

/**
 * Check if a given object implements the TournamentListResponseDto interface.
 */
export function instanceOfTournamentListResponseDto(value: object): value is TournamentListResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function TournamentListResponseDtoFromJSON(json: any): TournamentListResponseDto {
    return TournamentListResponseDtoFromJSONTyped(json, false);
}

export function TournamentListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TournamentListItemDtoFromJSON)),
        'pagination': PaginationDtoFromJSON(json['pagination']),
    };
}

export function TournamentListResponseDtoToJSON(json: any): TournamentListResponseDto {
    return TournamentListResponseDtoToJSONTyped(json, false);
}

export function TournamentListResponseDtoToJSONTyped(value?: TournamentListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TournamentListItemDtoToJSON)),
        'pagination': PaginationDtoToJSON(value['pagination']),
    };
}

