/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizerSummaryDto } from './OrganizerSummaryDto';
import {
    OrganizerSummaryDtoFromJSON,
    OrganizerSummaryDtoFromJSONTyped,
    OrganizerSummaryDtoToJSON,
    OrganizerSummaryDtoToJSONTyped,
} from './OrganizerSummaryDto';
import type { TournamentCategoryDto } from './TournamentCategoryDto';
import {
    TournamentCategoryDtoFromJSON,
    TournamentCategoryDtoFromJSONTyped,
    TournamentCategoryDtoToJSON,
    TournamentCategoryDtoToJSONTyped,
} from './TournamentCategoryDto';
import type { SportDto } from './SportDto';
import {
    SportDtoFromJSON,
    SportDtoFromJSONTyped,
    SportDtoToJSON,
    SportDtoToJSONTyped,
} from './SportDto';
import type { TournamentMediaDto } from './TournamentMediaDto';
import {
    TournamentMediaDtoFromJSON,
    TournamentMediaDtoFromJSONTyped,
    TournamentMediaDtoToJSON,
    TournamentMediaDtoToJSONTyped,
} from './TournamentMediaDto';
import type { CityDto } from './CityDto';
import {
    CityDtoFromJSON,
    CityDtoFromJSONTyped,
    CityDtoToJSON,
    CityDtoToJSONTyped,
} from './CityDto';
import type { VenueDto } from './VenueDto';
import {
    VenueDtoFromJSON,
    VenueDtoFromJSONTyped,
    VenueDtoToJSON,
    VenueDtoToJSONTyped,
} from './VenueDto';

/**
 * 
 * @export
 * @interface TournamentDetailDto
 */
export interface TournamentDetailDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    shortDescription?: string | null;
    /**
     * 
     * @type {SportDto}
     * @memberof TournamentDetailDto
     */
    sport: SportDto;
    /**
     * 
     * @type {CityDto}
     * @memberof TournamentDetailDto
     */
    city: CityDto;
    /**
     * 
     * @type {VenueDto}
     * @memberof TournamentDetailDto
     */
    venue?: VenueDto | null;
    /**
     * 
     * @type {OrganizerSummaryDto}
     * @memberof TournamentDetailDto
     */
    organizer: OrganizerSummaryDto;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    startsAt: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    endsAt: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    registrationOpensAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    registrationClosesAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    registrationAvailability: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    status: string;
    /**
     * 
     * @type {Array<TournamentCategoryDto>}
     * @memberof TournamentDetailDto
     */
    categories: Array<TournamentCategoryDto>;
    /**
     * 
     * @type {Array<TournamentMediaDto>}
     * @memberof TournamentDetailDto
     */
    media: Array<TournamentMediaDto>;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TournamentDetailDto
     */
    maxParticipants?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TournamentDetailDto
     */
    publishedAt?: string | null;
}

/**
 * Check if a given object implements the TournamentDetailDto interface.
 */
export function instanceOfTournamentDetailDto(value: object): value is TournamentDetailDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sport' in value) || value['sport'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('organizer' in value) || value['organizer'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('endsAt' in value) || value['endsAt'] === undefined) return false;
    if (!('registrationAvailability' in value) || value['registrationAvailability'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function TournamentDetailDtoFromJSON(json: any): TournamentDetailDto {
    return TournamentDetailDtoFromJSONTyped(json, false);
}

export function TournamentDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
        'sport': SportDtoFromJSON(json['sport']),
        'city': CityDtoFromJSON(json['city']),
        'venue': json['venue'] == null ? undefined : VenueDtoFromJSON(json['venue']),
        'organizer': OrganizerSummaryDtoFromJSON(json['organizer']),
        'startsAt': json['starts_at'],
        'endsAt': json['ends_at'],
        'registrationOpensAt': json['registration_opens_at'] == null ? undefined : json['registration_opens_at'],
        'registrationClosesAt': json['registration_closes_at'] == null ? undefined : json['registration_closes_at'],
        'registrationAvailability': json['registration_availability'],
        'status': json['status'],
        'categories': ((json['categories'] as Array<any>).map(TournamentCategoryDtoFromJSON)),
        'media': ((json['media'] as Array<any>).map(TournamentMediaDtoFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'maxParticipants': json['max_participants'] == null ? undefined : json['max_participants'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
    };
}

export function TournamentDetailDtoToJSON(json: any): TournamentDetailDto {
    return TournamentDetailDtoToJSONTyped(json, false);
}

export function TournamentDetailDtoToJSONTyped(value?: TournamentDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'short_description': value['shortDescription'],
        'sport': SportDtoToJSON(value['sport']),
        'city': CityDtoToJSON(value['city']),
        'venue': VenueDtoToJSON(value['venue']),
        'organizer': OrganizerSummaryDtoToJSON(value['organizer']),
        'starts_at': value['startsAt'],
        'ends_at': value['endsAt'],
        'registration_opens_at': value['registrationOpensAt'],
        'registration_closes_at': value['registrationClosesAt'],
        'registration_availability': value['registrationAvailability'],
        'status': value['status'],
        'categories': ((value['categories'] as Array<any>).map(TournamentCategoryDtoToJSON)),
        'media': ((value['media'] as Array<any>).map(TournamentMediaDtoToJSON)),
        'description': value['description'],
        'max_participants': value['maxParticipants'],
        'published_at': value['publishedAt'],
    };
}

