/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TournamentListResponseDto } from './TournamentListResponseDto';
import {
    TournamentListResponseDtoFromJSON,
    TournamentListResponseDtoFromJSONTyped,
    TournamentListResponseDtoToJSON,
    TournamentListResponseDtoToJSONTyped,
} from './TournamentListResponseDto';

/**
 * 
 * @export
 * @interface TournamentListApiResponseDto
 */
export interface TournamentListApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentListApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentListApiResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentListApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {TournamentListResponseDto}
     * @memberof TournamentListApiResponseDto
     */
    data: TournamentListResponseDto | null;
    /**
     * 
     * @type {object}
     * @memberof TournamentListApiResponseDto
     */
    error: object | null;
}

/**
 * Check if a given object implements the TournamentListApiResponseDto interface.
 */
export function instanceOfTournamentListApiResponseDto(value: object): value is TournamentListApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function TournamentListApiResponseDtoFromJSON(json: any): TournamentListApiResponseDto {
    return TournamentListApiResponseDtoFromJSONTyped(json, false);
}

export function TournamentListApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentListApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'status': json['status'],
        'message': json['message'],
        'data': TournamentListResponseDtoFromJSON(json['data']),
        'error': json['error'],
    };
}

export function TournamentListApiResponseDtoToJSON(json: any): TournamentListApiResponseDto {
    return TournamentListApiResponseDtoToJSONTyped(json, false);
}

export function TournamentListApiResponseDtoToJSONTyped(value?: TournamentListApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': TournamentListResponseDtoToJSON(value['data']),
        'error': value['error'],
    };
}

