/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentMediaDto
 */
export interface TournamentMediaDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentMediaDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentMediaDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentMediaDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentMediaDto
     */
    altText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TournamentMediaDto
     */
    sortOrder: number;
}

/**
 * Check if a given object implements the TournamentMediaDto interface.
 */
export function instanceOfTournamentMediaDto(value: object): value is TournamentMediaDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function TournamentMediaDtoFromJSON(json: any): TournamentMediaDto {
    return TournamentMediaDtoFromJSONTyped(json, false);
}

export function TournamentMediaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentMediaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'url': json['url'],
        'altText': json['alt_text'] == null ? undefined : json['alt_text'],
        'sortOrder': json['sort_order'],
    };
}

export function TournamentMediaDtoToJSON(json: any): TournamentMediaDto {
    return TournamentMediaDtoToJSONTyped(json, false);
}

export function TournamentMediaDtoToJSONTyped(value?: TournamentMediaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'url': value['url'],
        'alt_text': value['altText'],
        'sort_order': value['sortOrder'],
    };
}

