/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizerTournamentRequestDto
 */
export interface UpdateOrganizerTournamentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    shortDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    sportId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    cityId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    venueId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    startsAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    endsAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    registrationOpensAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    registrationClosesAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateOrganizerTournamentRequestDto
     */
    maxParticipants?: number | null;
}

/**
 * Check if a given object implements the UpdateOrganizerTournamentRequestDto interface.
 */
export function instanceOfUpdateOrganizerTournamentRequestDto(value: object): value is UpdateOrganizerTournamentRequestDto {
    return true;
}

export function UpdateOrganizerTournamentRequestDtoFromJSON(json: any): UpdateOrganizerTournamentRequestDto {
    return UpdateOrganizerTournamentRequestDtoFromJSONTyped(json, false);
}

export function UpdateOrganizerTournamentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizerTournamentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
        'description': json['description'] == null ? undefined : json['description'],
        'sportId': json['sport_id'] == null ? undefined : json['sport_id'],
        'cityId': json['city_id'] == null ? undefined : json['city_id'],
        'venueId': json['venue_id'] == null ? undefined : json['venue_id'],
        'startsAt': json['starts_at'] == null ? undefined : json['starts_at'],
        'endsAt': json['ends_at'] == null ? undefined : json['ends_at'],
        'registrationOpensAt': json['registration_opens_at'] == null ? undefined : json['registration_opens_at'],
        'registrationClosesAt': json['registration_closes_at'] == null ? undefined : json['registration_closes_at'],
        'maxParticipants': json['max_participants'] == null ? undefined : json['max_participants'],
    };
}

export function UpdateOrganizerTournamentRequestDtoToJSON(json: any): UpdateOrganizerTournamentRequestDto {
    return UpdateOrganizerTournamentRequestDtoToJSONTyped(json, false);
}

export function UpdateOrganizerTournamentRequestDtoToJSONTyped(value?: UpdateOrganizerTournamentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'short_description': value['shortDescription'],
        'description': value['description'],
        'sport_id': value['sportId'],
        'city_id': value['cityId'],
        'venue_id': value['venueId'],
        'starts_at': value['startsAt'],
        'ends_at': value['endsAt'],
        'registration_opens_at': value['registrationOpensAt'],
        'registration_closes_at': value['registrationClosesAt'],
        'max_participants': value['maxParticipants'],
    };
}

