/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTeamMemberRequestDto
 */
export interface UpdateTeamMemberRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamMemberRequestDto
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamMemberRequestDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamMemberRequestDto
     */
    phone?: string | null;
    /**
     * 
     * @type {UpdateTeamMemberRequestDtoRoleEnum}
     * @memberof UpdateTeamMemberRequestDto
     */
    role?: UpdateTeamMemberRequestDtoRoleEnum;
}


/**
 * @export
 */
export const UpdateTeamMemberRequestDtoRoleEnum = {
    Captain: 'CAPTAIN',
    Player: 'PLAYER',
    Substitute: 'SUBSTITUTE'
} as const;
export type UpdateTeamMemberRequestDtoRoleEnum = typeof UpdateTeamMemberRequestDtoRoleEnum[keyof typeof UpdateTeamMemberRequestDtoRoleEnum];


/**
 * Check if a given object implements the UpdateTeamMemberRequestDto interface.
 */
export function instanceOfUpdateTeamMemberRequestDto(value: object): value is UpdateTeamMemberRequestDto {
    return true;
}

export function UpdateTeamMemberRequestDtoFromJSON(json: any): UpdateTeamMemberRequestDto {
    return UpdateTeamMemberRequestDtoFromJSONTyped(json, false);
}

export function UpdateTeamMemberRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTeamMemberRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UpdateTeamMemberRequestDtoToJSON(json: any): UpdateTeamMemberRequestDto {
    return UpdateTeamMemberRequestDtoToJSONTyped(json, false);
}

export function UpdateTeamMemberRequestDtoToJSONTyped(value?: UpdateTeamMemberRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'role': value['role'],
    };
}

