/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueDto
 */
export interface VenueDto {
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    latitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueDto
     */
    longitude?: string | null;
}

/**
 * Check if a given object implements the VenueDto interface.
 */
export function instanceOfVenueDto(value: object): value is VenueDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function VenueDtoFromJSON(json: any): VenueDto {
    return VenueDtoFromJSONTyped(json, false);
}

export function VenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'address': json['address'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function VenueDtoToJSON(json: any): VenueDto {
    return VenueDtoToJSONTyped(json, false);
}

export function VenueDtoToJSONTyped(value?: VenueDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'address': value['address'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

