/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminAuditEventsApiResponseDto,
    AdminAuditEventsApiResponseDtoFromJSON,
    AdminAuditEventsApiResponseDtoToJSON,
} from '../models/AdminAuditEventsApiResponseDto';
import {
    type AdminDashboardApiResponseDto,
    AdminDashboardApiResponseDtoFromJSON,
    AdminDashboardApiResponseDtoToJSON,
} from '../models/AdminDashboardApiResponseDto';
import {
    type AdminNotificationApiResponseDto,
    AdminNotificationApiResponseDtoFromJSON,
    AdminNotificationApiResponseDtoToJSON,
} from '../models/AdminNotificationApiResponseDto';
import {
    type AdminNotificationsApiResponseDto,
    AdminNotificationsApiResponseDtoFromJSON,
    AdminNotificationsApiResponseDtoToJSON,
} from '../models/AdminNotificationsApiResponseDto';
import {
    type AdminOrganizerApiResponseDto,
    AdminOrganizerApiResponseDtoFromJSON,
    AdminOrganizerApiResponseDtoToJSON,
} from '../models/AdminOrganizerApiResponseDto';
import {
    type AdminOrganizerDetailApiResponseDto,
    AdminOrganizerDetailApiResponseDtoFromJSON,
    AdminOrganizerDetailApiResponseDtoToJSON,
} from '../models/AdminOrganizerDetailApiResponseDto';
import {
    type AdminOrganizersApiResponseDto,
    AdminOrganizersApiResponseDtoFromJSON,
    AdminOrganizersApiResponseDtoToJSON,
} from '../models/AdminOrganizersApiResponseDto';
import {
    type AdminPaymentDetailApiResponseDto,
    AdminPaymentDetailApiResponseDtoFromJSON,
    AdminPaymentDetailApiResponseDtoToJSON,
} from '../models/AdminPaymentDetailApiResponseDto';
import {
    type AdminPaymentsApiResponseDto,
    AdminPaymentsApiResponseDtoFromJSON,
    AdminPaymentsApiResponseDtoToJSON,
} from '../models/AdminPaymentsApiResponseDto';
import {
    type AdminReconciliationRunsApiResponseDto,
    AdminReconciliationRunsApiResponseDtoFromJSON,
    AdminReconciliationRunsApiResponseDtoToJSON,
} from '../models/AdminReconciliationRunsApiResponseDto';
import {
    type AdminRegistrationsApiResponseDto,
    AdminRegistrationsApiResponseDtoFromJSON,
    AdminRegistrationsApiResponseDtoToJSON,
} from '../models/AdminRegistrationsApiResponseDto';
import {
    type AdminTournamentsApiResponseDto,
    AdminTournamentsApiResponseDtoFromJSON,
    AdminTournamentsApiResponseDtoToJSON,
} from '../models/AdminTournamentsApiResponseDto';
import {
    type AdminUsersApiResponseDto,
    AdminUsersApiResponseDtoFromJSON,
    AdminUsersApiResponseDtoToJSON,
} from '../models/AdminUsersApiResponseDto';
import {
    type RejectOrganizerVerificationRequestDto,
    RejectOrganizerVerificationRequestDtoFromJSON,
    RejectOrganizerVerificationRequestDtoToJSON,
} from '../models/RejectOrganizerVerificationRequestDto';
import {
    type SkipNotificationRequestDto,
    SkipNotificationRequestDtoFromJSON,
    SkipNotificationRequestDtoToJSON,
} from '../models/SkipNotificationRequestDto';

export interface AdminControllerExportAuditEventsRequest {
    page?: number;
    limit?: number;
    search?: string;
    entityType?: string;
    action?: string;
}

export interface AdminControllerExportNotificationsRequest {
    page?: number;
    limit?: number;
    search?: string;
    type?: string;
    status?: AdminControllerExportNotificationsStatusEnum;
    channel?: AdminControllerExportNotificationsChannelEnum;
}

export interface AdminControllerExportOrganizersRequest {
    page?: number;
    limit?: number;
    search?: string;
    verificationStatus?: AdminControllerExportOrganizersVerificationStatusEnum;
}

export interface AdminControllerExportPaymentsRequest {
    page?: number;
    limit?: number;
    search?: string;
    provider?: AdminControllerExportPaymentsProviderEnum;
    status?: AdminControllerExportPaymentsStatusEnum;
    tournamentId?: string;
    registrationId?: string;
}

export interface AdminControllerExportRegistrationsRequest {
    page?: number;
    limit?: number;
    search?: string;
    status?: AdminControllerExportRegistrationsStatusEnum;
    paymentStatus?: AdminControllerExportRegistrationsPaymentStatusEnum;
    tournamentId?: string;
}

export interface AdminControllerExportTournamentsRequest {
    page?: number;
    limit?: number;
    search?: string;
    status?: AdminControllerExportTournamentsStatusEnum;
    organizerId?: string;
}

export interface AdminControllerExportUsersRequest {
    page?: number;
    limit?: number;
    search?: string;
    role?: AdminControllerExportUsersRoleEnum;
}

export interface AdminControllerFindOrganizerDetailRequest {
    organizerId: string;
}

export interface AdminControllerFindPaymentDetailRequest {
    paymentRecordId: string;
}

export interface AdminControllerListAuditEventsRequest {
    page?: number;
    limit?: number;
    search?: string;
    entityType?: string;
    action?: string;
}

export interface AdminControllerListNotificationsRequest {
    page?: number;
    limit?: number;
    search?: string;
    type?: string;
    status?: AdminControllerListNotificationsStatusEnum;
    channel?: AdminControllerListNotificationsChannelEnum;
}

export interface AdminControllerListOrganizersRequest {
    page?: number;
    limit?: number;
    search?: string;
    verificationStatus?: AdminControllerListOrganizersVerificationStatusEnum;
}

export interface AdminControllerListPaymentsRequest {
    page?: number;
    limit?: number;
    search?: string;
    provider?: AdminControllerListPaymentsProviderEnum;
    status?: AdminControllerListPaymentsStatusEnum;
    tournamentId?: string;
    registrationId?: string;
}

export interface AdminControllerListReconciliationRunsRequest {
    page?: number;
    limit?: number;
    search?: string;
    provider?: AdminControllerListReconciliationRunsProviderEnum;
    status?: AdminControllerListReconciliationRunsStatusEnum;
}

export interface AdminControllerListRegistrationsRequest {
    page?: number;
    limit?: number;
    search?: string;
    status?: AdminControllerListRegistrationsStatusEnum;
    paymentStatus?: AdminControllerListRegistrationsPaymentStatusEnum;
    tournamentId?: string;
}

export interface AdminControllerListTournamentsRequest {
    page?: number;
    limit?: number;
    search?: string;
    status?: AdminControllerListTournamentsStatusEnum;
    organizerId?: string;
}

export interface AdminControllerListUsersRequest {
    page?: number;
    limit?: number;
    search?: string;
    role?: AdminControllerListUsersRoleEnum;
}

export interface AdminControllerRejectOrganizerRequest {
    organizerId: string;
    rejectOrganizerVerificationRequestDto: RejectOrganizerVerificationRequestDto;
}

export interface AdminControllerResetOrganizerVerificationRequest {
    organizerId: string;
}

export interface AdminControllerRetryNotificationRequest {
    notificationId: string;
}

export interface AdminControllerSkipNotificationRequest {
    notificationId: string;
    skipNotificationRequestDto: SkipNotificationRequestDto;
}

export interface AdminControllerVerifyOrganizerRequest {
    organizerId: string;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Creates request options for adminControllerExportAuditEvents without sending the request
     */
    async adminControllerExportAuditEventsRequestOpts(requestParameters: AdminControllerExportAuditEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['entityType'] != null) {
            queryParameters['entity_type'] = requestParameters['entityType'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/audit-events/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export sanitized audit event summary as CSV
     */
    async adminControllerExportAuditEventsRaw(requestParameters: AdminControllerExportAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportAuditEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export sanitized audit event summary as CSV
     */
    async adminControllerExportAuditEvents(requestParameters: AdminControllerExportAuditEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportAuditEventsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportNotifications without sending the request
     */
    async adminControllerExportNotificationsRequestOpts(requestParameters: AdminControllerExportNotificationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['channel'] != null) {
            queryParameters['channel'] = requestParameters['channel'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/notifications/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe notification outbox summary as CSV
     */
    async adminControllerExportNotificationsRaw(requestParameters: AdminControllerExportNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe notification outbox summary as CSV
     */
    async adminControllerExportNotifications(requestParameters: AdminControllerExportNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportNotificationsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportOrganizers without sending the request
     */
    async adminControllerExportOrganizersRequestOpts(requestParameters: AdminControllerExportOrganizersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['verificationStatus'] != null) {
            queryParameters['verification_status'] = requestParameters['verificationStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe organizer verification list as CSV
     */
    async adminControllerExportOrganizersRaw(requestParameters: AdminControllerExportOrganizersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportOrganizersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe organizer verification list as CSV
     */
    async adminControllerExportOrganizers(requestParameters: AdminControllerExportOrganizersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportOrganizersRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportPayments without sending the request
     */
    async adminControllerExportPaymentsRequestOpts(requestParameters: AdminControllerExportPaymentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['tournamentId'] != null) {
            queryParameters['tournament_id'] = requestParameters['tournamentId'];
        }

        if (requestParameters['registrationId'] != null) {
            queryParameters['registration_id'] = requestParameters['registrationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/payments/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe payment overview as CSV
     */
    async adminControllerExportPaymentsRaw(requestParameters: AdminControllerExportPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportPaymentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe payment overview as CSV
     */
    async adminControllerExportPayments(requestParameters: AdminControllerExportPaymentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportPaymentsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportRegistrations without sending the request
     */
    async adminControllerExportRegistrationsRequestOpts(requestParameters: AdminControllerExportRegistrationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['paymentStatus'] != null) {
            queryParameters['payment_status'] = requestParameters['paymentStatus'];
        }

        if (requestParameters['tournamentId'] != null) {
            queryParameters['tournament_id'] = requestParameters['tournamentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/registrations/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe registration overview as CSV
     */
    async adminControllerExportRegistrationsRaw(requestParameters: AdminControllerExportRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportRegistrationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe registration overview as CSV
     */
    async adminControllerExportRegistrations(requestParameters: AdminControllerExportRegistrationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportRegistrationsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportTournaments without sending the request
     */
    async adminControllerExportTournamentsRequestOpts(requestParameters: AdminControllerExportTournamentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['organizerId'] != null) {
            queryParameters['organizer_id'] = requestParameters['organizerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/tournaments/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe tournament overview as CSV
     */
    async adminControllerExportTournamentsRaw(requestParameters: AdminControllerExportTournamentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportTournamentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe tournament overview as CSV
     */
    async adminControllerExportTournaments(requestParameters: AdminControllerExportTournamentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportTournamentsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerExportUsers without sending the request
     */
    async adminControllerExportUsersRequestOpts(requestParameters: AdminControllerExportUsersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users/export.csv`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export safe platform users list as CSV
     */
    async adminControllerExportUsersRaw(requestParameters: AdminControllerExportUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.adminControllerExportUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export safe platform users list as CSV
     */
    async adminControllerExportUsers(requestParameters: AdminControllerExportUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerExportUsersRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for adminControllerFindOrganizerDetail without sending the request
     */
    async adminControllerFindOrganizerDetailRequestOpts(requestParameters: AdminControllerFindOrganizerDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizerId'] == null) {
            throw new runtime.RequiredError(
                'organizerId',
                'Required parameter "organizerId" was null or undefined when calling adminControllerFindOrganizerDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers/{organizerId}`;
        urlPath = urlPath.replace('{organizerId}', encodeURIComponent(String(requestParameters['organizerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get read-only organizer verification detail for support review
     */
    async adminControllerFindOrganizerDetailRaw(requestParameters: AdminControllerFindOrganizerDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrganizerDetailApiResponseDto>> {
        const requestOptions = await this.adminControllerFindOrganizerDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrganizerDetailApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get read-only organizer verification detail for support review
     */
    async adminControllerFindOrganizerDetail(requestParameters: AdminControllerFindOrganizerDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrganizerDetailApiResponseDto> {
        const response = await this.adminControllerFindOrganizerDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerFindPaymentDetail without sending the request
     */
    async adminControllerFindPaymentDetailRequestOpts(requestParameters: AdminControllerFindPaymentDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentRecordId'] == null) {
            throw new runtime.RequiredError(
                'paymentRecordId',
                'Required parameter "paymentRecordId" was null or undefined when calling adminControllerFindPaymentDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/payments/{paymentRecordId}`;
        urlPath = urlPath.replace('{paymentRecordId}', encodeURIComponent(String(requestParameters['paymentRecordId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get read-only support diagnostics for one payment record
     */
    async adminControllerFindPaymentDetailRaw(requestParameters: AdminControllerFindPaymentDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminPaymentDetailApiResponseDto>> {
        const requestOptions = await this.adminControllerFindPaymentDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminPaymentDetailApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get read-only support diagnostics for one payment record
     */
    async adminControllerFindPaymentDetail(requestParameters: AdminControllerFindPaymentDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminPaymentDetailApiResponseDto> {
        const response = await this.adminControllerFindPaymentDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerGetDashboard without sending the request
     */
    async adminControllerGetDashboardRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/dashboard`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get read-only platform support dashboard summary
     */
    async adminControllerGetDashboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminDashboardApiResponseDto>> {
        const requestOptions = await this.adminControllerGetDashboardRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminDashboardApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get read-only platform support dashboard summary
     */
    async adminControllerGetDashboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminDashboardApiResponseDto> {
        const response = await this.adminControllerGetDashboardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListAuditEvents without sending the request
     */
    async adminControllerListAuditEventsRequestOpts(requestParameters: AdminControllerListAuditEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['entityType'] != null) {
            queryParameters['entity_type'] = requestParameters['entityType'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/audit-events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List sanitized audit events for support inspection
     */
    async adminControllerListAuditEventsRaw(requestParameters: AdminControllerListAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAuditEventsApiResponseDto>> {
        const requestOptions = await this.adminControllerListAuditEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminAuditEventsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List sanitized audit events for support inspection
     */
    async adminControllerListAuditEvents(requestParameters: AdminControllerListAuditEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAuditEventsApiResponseDto> {
        const response = await this.adminControllerListAuditEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListNotifications without sending the request
     */
    async adminControllerListNotificationsRequestOpts(requestParameters: AdminControllerListNotificationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['channel'] != null) {
            queryParameters['channel'] = requestParameters['channel'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List notification outbox rows for support inspection
     */
    async adminControllerListNotificationsRaw(requestParameters: AdminControllerListNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminNotificationsApiResponseDto>> {
        const requestOptions = await this.adminControllerListNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminNotificationsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List notification outbox rows for support inspection
     */
    async adminControllerListNotifications(requestParameters: AdminControllerListNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminNotificationsApiResponseDto> {
        const response = await this.adminControllerListNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListOrganizers without sending the request
     */
    async adminControllerListOrganizersRequestOpts(requestParameters: AdminControllerListOrganizersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['verificationStatus'] != null) {
            queryParameters['verification_status'] = requestParameters['verificationStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List organizer profiles for support inspection
     */
    async adminControllerListOrganizersRaw(requestParameters: AdminControllerListOrganizersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrganizersApiResponseDto>> {
        const requestOptions = await this.adminControllerListOrganizersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrganizersApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List organizer profiles for support inspection
     */
    async adminControllerListOrganizers(requestParameters: AdminControllerListOrganizersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrganizersApiResponseDto> {
        const response = await this.adminControllerListOrganizersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListPayments without sending the request
     */
    async adminControllerListPaymentsRequestOpts(requestParameters: AdminControllerListPaymentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['tournamentId'] != null) {
            queryParameters['tournament_id'] = requestParameters['tournamentId'];
        }

        if (requestParameters['registrationId'] != null) {
            queryParameters['registration_id'] = requestParameters['registrationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List payment records for support inspection
     */
    async adminControllerListPaymentsRaw(requestParameters: AdminControllerListPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminPaymentsApiResponseDto>> {
        const requestOptions = await this.adminControllerListPaymentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminPaymentsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List payment records for support inspection
     */
    async adminControllerListPayments(requestParameters: AdminControllerListPaymentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminPaymentsApiResponseDto> {
        const response = await this.adminControllerListPaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListReconciliationRuns without sending the request
     */
    async adminControllerListReconciliationRunsRequestOpts(requestParameters: AdminControllerListReconciliationRunsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/reconciliation-runs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List payment reconciliation runs for support inspection
     */
    async adminControllerListReconciliationRunsRaw(requestParameters: AdminControllerListReconciliationRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminReconciliationRunsApiResponseDto>> {
        const requestOptions = await this.adminControllerListReconciliationRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminReconciliationRunsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List payment reconciliation runs for support inspection
     */
    async adminControllerListReconciliationRuns(requestParameters: AdminControllerListReconciliationRunsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminReconciliationRunsApiResponseDto> {
        const response = await this.adminControllerListReconciliationRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListRegistrations without sending the request
     */
    async adminControllerListRegistrationsRequestOpts(requestParameters: AdminControllerListRegistrationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['paymentStatus'] != null) {
            queryParameters['payment_status'] = requestParameters['paymentStatus'];
        }

        if (requestParameters['tournamentId'] != null) {
            queryParameters['tournament_id'] = requestParameters['tournamentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/registrations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List registrations for support inspection
     */
    async adminControllerListRegistrationsRaw(requestParameters: AdminControllerListRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRegistrationsApiResponseDto>> {
        const requestOptions = await this.adminControllerListRegistrationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminRegistrationsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List registrations for support inspection
     */
    async adminControllerListRegistrations(requestParameters: AdminControllerListRegistrationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRegistrationsApiResponseDto> {
        const response = await this.adminControllerListRegistrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListTournaments without sending the request
     */
    async adminControllerListTournamentsRequestOpts(requestParameters: AdminControllerListTournamentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['organizerId'] != null) {
            queryParameters['organizer_id'] = requestParameters['organizerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/tournaments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tournaments for support inspection
     */
    async adminControllerListTournamentsRaw(requestParameters: AdminControllerListTournamentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminTournamentsApiResponseDto>> {
        const requestOptions = await this.adminControllerListTournamentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminTournamentsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List tournaments for support inspection
     */
    async adminControllerListTournaments(requestParameters: AdminControllerListTournamentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminTournamentsApiResponseDto> {
        const response = await this.adminControllerListTournamentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerListUsers without sending the request
     */
    async adminControllerListUsersRequestOpts(requestParameters: AdminControllerListUsersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List platform users for support inspection
     */
    async adminControllerListUsersRaw(requestParameters: AdminControllerListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminUsersApiResponseDto>> {
        const requestOptions = await this.adminControllerListUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminUsersApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List platform users for support inspection
     */
    async adminControllerListUsers(requestParameters: AdminControllerListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminUsersApiResponseDto> {
        const response = await this.adminControllerListUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerRejectOrganizer without sending the request
     */
    async adminControllerRejectOrganizerRequestOpts(requestParameters: AdminControllerRejectOrganizerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizerId'] == null) {
            throw new runtime.RequiredError(
                'organizerId',
                'Required parameter "organizerId" was null or undefined when calling adminControllerRejectOrganizer().'
            );
        }

        if (requestParameters['rejectOrganizerVerificationRequestDto'] == null) {
            throw new runtime.RequiredError(
                'rejectOrganizerVerificationRequestDto',
                'Required parameter "rejectOrganizerVerificationRequestDto" was null or undefined when calling adminControllerRejectOrganizer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers/{organizerId}/reject`;
        urlPath = urlPath.replace('{organizerId}', encodeURIComponent(String(requestParameters['organizerId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RejectOrganizerVerificationRequestDtoToJSON(requestParameters['rejectOrganizerVerificationRequestDto']),
        };
    }

    /**
     * Reject an organizer verification request with audit trail
     */
    async adminControllerRejectOrganizerRaw(requestParameters: AdminControllerRejectOrganizerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrganizerApiResponseDto>> {
        const requestOptions = await this.adminControllerRejectOrganizerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrganizerApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Reject an organizer verification request with audit trail
     */
    async adminControllerRejectOrganizer(requestParameters: AdminControllerRejectOrganizerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrganizerApiResponseDto> {
        const response = await this.adminControllerRejectOrganizerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerResetOrganizerVerification without sending the request
     */
    async adminControllerResetOrganizerVerificationRequestOpts(requestParameters: AdminControllerResetOrganizerVerificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizerId'] == null) {
            throw new runtime.RequiredError(
                'organizerId',
                'Required parameter "organizerId" was null or undefined when calling adminControllerResetOrganizerVerification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers/{organizerId}/reset-verification`;
        urlPath = urlPath.replace('{organizerId}', encodeURIComponent(String(requestParameters['organizerId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reset organizer verification to pending with audit trail
     */
    async adminControllerResetOrganizerVerificationRaw(requestParameters: AdminControllerResetOrganizerVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrganizerApiResponseDto>> {
        const requestOptions = await this.adminControllerResetOrganizerVerificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrganizerApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Reset organizer verification to pending with audit trail
     */
    async adminControllerResetOrganizerVerification(requestParameters: AdminControllerResetOrganizerVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrganizerApiResponseDto> {
        const response = await this.adminControllerResetOrganizerVerificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerRetryNotification without sending the request
     */
    async adminControllerRetryNotificationRequestOpts(requestParameters: AdminControllerRetryNotificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling adminControllerRetryNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/notifications/{notificationId}/retry`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return a failed or skipped notification to pending for processor retry
     */
    async adminControllerRetryNotificationRaw(requestParameters: AdminControllerRetryNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminNotificationApiResponseDto>> {
        const requestOptions = await this.adminControllerRetryNotificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminNotificationApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Return a failed or skipped notification to pending for processor retry
     */
    async adminControllerRetryNotification(requestParameters: AdminControllerRetryNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminNotificationApiResponseDto> {
        const response = await this.adminControllerRetryNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerSkipNotification without sending the request
     */
    async adminControllerSkipNotificationRequestOpts(requestParameters: AdminControllerSkipNotificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling adminControllerSkipNotification().'
            );
        }

        if (requestParameters['skipNotificationRequestDto'] == null) {
            throw new runtime.RequiredError(
                'skipNotificationRequestDto',
                'Required parameter "skipNotificationRequestDto" was null or undefined when calling adminControllerSkipNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/notifications/{notificationId}/skip`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SkipNotificationRequestDtoToJSON(requestParameters['skipNotificationRequestDto']),
        };
    }

    /**
     * Mark a pending or failed notification as skipped with audit trail
     */
    async adminControllerSkipNotificationRaw(requestParameters: AdminControllerSkipNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminNotificationApiResponseDto>> {
        const requestOptions = await this.adminControllerSkipNotificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminNotificationApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Mark a pending or failed notification as skipped with audit trail
     */
    async adminControllerSkipNotification(requestParameters: AdminControllerSkipNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminNotificationApiResponseDto> {
        const response = await this.adminControllerSkipNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminControllerVerifyOrganizer without sending the request
     */
    async adminControllerVerifyOrganizerRequestOpts(requestParameters: AdminControllerVerifyOrganizerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizerId'] == null) {
            throw new runtime.RequiredError(
                'organizerId',
                'Required parameter "organizerId" was null or undefined when calling adminControllerVerifyOrganizer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizers/{organizerId}/verify`;
        urlPath = urlPath.replace('{organizerId}', encodeURIComponent(String(requestParameters['organizerId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verify an organizer profile with audit trail
     */
    async adminControllerVerifyOrganizerRaw(requestParameters: AdminControllerVerifyOrganizerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrganizerApiResponseDto>> {
        const requestOptions = await this.adminControllerVerifyOrganizerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrganizerApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Verify an organizer profile with audit trail
     */
    async adminControllerVerifyOrganizer(requestParameters: AdminControllerVerifyOrganizerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrganizerApiResponseDto> {
        const response = await this.adminControllerVerifyOrganizerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AdminControllerExportNotificationsStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Sent: 'sent',
    Failed: 'failed',
    Skipped: 'skipped'
} as const;
export type AdminControllerExportNotificationsStatusEnum = typeof AdminControllerExportNotificationsStatusEnum[keyof typeof AdminControllerExportNotificationsStatusEnum];
/**
 * @export
 */
export const AdminControllerExportNotificationsChannelEnum = {
    Email: 'email'
} as const;
export type AdminControllerExportNotificationsChannelEnum = typeof AdminControllerExportNotificationsChannelEnum[keyof typeof AdminControllerExportNotificationsChannelEnum];
/**
 * @export
 */
export const AdminControllerExportOrganizersVerificationStatusEnum = {
    Pending: 'pending',
    Verified: 'verified',
    Rejected: 'rejected'
} as const;
export type AdminControllerExportOrganizersVerificationStatusEnum = typeof AdminControllerExportOrganizersVerificationStatusEnum[keyof typeof AdminControllerExportOrganizersVerificationStatusEnum];
/**
 * @export
 */
export const AdminControllerExportPaymentsProviderEnum = {
    Manual: 'manual',
    Mock: 'mock',
    Razorpay: 'razorpay',
    FutureProvider: 'future_provider'
} as const;
export type AdminControllerExportPaymentsProviderEnum = typeof AdminControllerExportPaymentsProviderEnum[keyof typeof AdminControllerExportPaymentsProviderEnum];
/**
 * @export
 */
export const AdminControllerExportPaymentsStatusEnum = {
    NotRequired: 'not_required',
    PendingOffline: 'pending_offline',
    Paid: 'paid',
    Failed: 'failed',
    Refunded: 'refunded',
    Waived: 'waived'
} as const;
export type AdminControllerExportPaymentsStatusEnum = typeof AdminControllerExportPaymentsStatusEnum[keyof typeof AdminControllerExportPaymentsStatusEnum];
/**
 * @export
 */
export const AdminControllerExportRegistrationsStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Rejected: 'rejected',
    Cancelled: 'cancelled'
} as const;
export type AdminControllerExportRegistrationsStatusEnum = typeof AdminControllerExportRegistrationsStatusEnum[keyof typeof AdminControllerExportRegistrationsStatusEnum];
/**
 * @export
 */
export const AdminControllerExportRegistrationsPaymentStatusEnum = {
    NotRequired: 'not_required',
    PendingOffline: 'pending_offline',
    Paid: 'paid',
    Failed: 'failed',
    Refunded: 'refunded',
    Waived: 'waived'
} as const;
export type AdminControllerExportRegistrationsPaymentStatusEnum = typeof AdminControllerExportRegistrationsPaymentStatusEnum[keyof typeof AdminControllerExportRegistrationsPaymentStatusEnum];
/**
 * @export
 */
export const AdminControllerExportTournamentsStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived',
    Blocked: 'blocked'
} as const;
export type AdminControllerExportTournamentsStatusEnum = typeof AdminControllerExportTournamentsStatusEnum[keyof typeof AdminControllerExportTournamentsStatusEnum];
/**
 * @export
 */
export const AdminControllerExportUsersRoleEnum = {
    Player: 'PLAYER',
    Organizer: 'ORGANIZER',
    Admin: 'ADMIN'
} as const;
export type AdminControllerExportUsersRoleEnum = typeof AdminControllerExportUsersRoleEnum[keyof typeof AdminControllerExportUsersRoleEnum];
/**
 * @export
 */
export const AdminControllerListNotificationsStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Sent: 'sent',
    Failed: 'failed',
    Skipped: 'skipped'
} as const;
export type AdminControllerListNotificationsStatusEnum = typeof AdminControllerListNotificationsStatusEnum[keyof typeof AdminControllerListNotificationsStatusEnum];
/**
 * @export
 */
export const AdminControllerListNotificationsChannelEnum = {
    Email: 'email'
} as const;
export type AdminControllerListNotificationsChannelEnum = typeof AdminControllerListNotificationsChannelEnum[keyof typeof AdminControllerListNotificationsChannelEnum];
/**
 * @export
 */
export const AdminControllerListOrganizersVerificationStatusEnum = {
    Pending: 'pending',
    Verified: 'verified',
    Rejected: 'rejected'
} as const;
export type AdminControllerListOrganizersVerificationStatusEnum = typeof AdminControllerListOrganizersVerificationStatusEnum[keyof typeof AdminControllerListOrganizersVerificationStatusEnum];
/**
 * @export
 */
export const AdminControllerListPaymentsProviderEnum = {
    Manual: 'manual',
    Mock: 'mock',
    Razorpay: 'razorpay',
    FutureProvider: 'future_provider'
} as const;
export type AdminControllerListPaymentsProviderEnum = typeof AdminControllerListPaymentsProviderEnum[keyof typeof AdminControllerListPaymentsProviderEnum];
/**
 * @export
 */
export const AdminControllerListPaymentsStatusEnum = {
    NotRequired: 'not_required',
    PendingOffline: 'pending_offline',
    Paid: 'paid',
    Failed: 'failed',
    Refunded: 'refunded',
    Waived: 'waived'
} as const;
export type AdminControllerListPaymentsStatusEnum = typeof AdminControllerListPaymentsStatusEnum[keyof typeof AdminControllerListPaymentsStatusEnum];
/**
 * @export
 */
export const AdminControllerListReconciliationRunsProviderEnum = {
    Manual: 'manual',
    Mock: 'mock',
    Razorpay: 'razorpay',
    FutureProvider: 'future_provider'
} as const;
export type AdminControllerListReconciliationRunsProviderEnum = typeof AdminControllerListReconciliationRunsProviderEnum[keyof typeof AdminControllerListReconciliationRunsProviderEnum];
/**
 * @export
 */
export const AdminControllerListReconciliationRunsStatusEnum = {
    Started: 'started',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type AdminControllerListReconciliationRunsStatusEnum = typeof AdminControllerListReconciliationRunsStatusEnum[keyof typeof AdminControllerListReconciliationRunsStatusEnum];
/**
 * @export
 */
export const AdminControllerListRegistrationsStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Rejected: 'rejected',
    Cancelled: 'cancelled'
} as const;
export type AdminControllerListRegistrationsStatusEnum = typeof AdminControllerListRegistrationsStatusEnum[keyof typeof AdminControllerListRegistrationsStatusEnum];
/**
 * @export
 */
export const AdminControllerListRegistrationsPaymentStatusEnum = {
    NotRequired: 'not_required',
    PendingOffline: 'pending_offline',
    Paid: 'paid',
    Failed: 'failed',
    Refunded: 'refunded',
    Waived: 'waived'
} as const;
export type AdminControllerListRegistrationsPaymentStatusEnum = typeof AdminControllerListRegistrationsPaymentStatusEnum[keyof typeof AdminControllerListRegistrationsPaymentStatusEnum];
/**
 * @export
 */
export const AdminControllerListTournamentsStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived',
    Blocked: 'blocked'
} as const;
export type AdminControllerListTournamentsStatusEnum = typeof AdminControllerListTournamentsStatusEnum[keyof typeof AdminControllerListTournamentsStatusEnum];
/**
 * @export
 */
export const AdminControllerListUsersRoleEnum = {
    Player: 'PLAYER',
    Organizer: 'ORGANIZER',
    Admin: 'ADMIN'
} as const;
export type AdminControllerListUsersRoleEnum = typeof AdminControllerListUsersRoleEnum[keyof typeof AdminControllerListUsersRoleEnum];
