/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CitiesApiResponseDto,
    CitiesApiResponseDtoFromJSON,
    CitiesApiResponseDtoToJSON,
} from '../models/CitiesApiResponseDto';
import {
    type PublicFixtureSetListApiResponseDto,
    PublicFixtureSetListApiResponseDtoFromJSON,
    PublicFixtureSetListApiResponseDtoToJSON,
} from '../models/PublicFixtureSetListApiResponseDto';
import {
    type SportsApiResponseDto,
    SportsApiResponseDtoFromJSON,
    SportsApiResponseDtoToJSON,
} from '../models/SportsApiResponseDto';
import {
    type TournamentDetailApiResponseDto,
    TournamentDetailApiResponseDtoFromJSON,
    TournamentDetailApiResponseDtoToJSON,
} from '../models/TournamentDetailApiResponseDto';
import {
    type TournamentListApiResponseDto,
    TournamentListApiResponseDtoFromJSON,
    TournamentListApiResponseDtoToJSON,
} from '../models/TournamentListApiResponseDto';

export interface DiscoveryControllerFindTournamentDetailRequest {
    slugOrId: string;
}

export interface DiscoveryControllerFindTournamentFixturesRequest {
    slugOrId: string;
}

export interface DiscoveryControllerFindTournamentsRequest {
    city?: string;
    sport?: string;
    status?: DiscoveryControllerFindTournamentsStatusEnum;
    upcomingOnly?: boolean;
    startsFrom?: string;
    startsTo?: string;
    search?: string;
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class DiscoveryApi extends runtime.BaseAPI {

    /**
     * Creates request options for discoveryControllerFindCities without sending the request
     */
    async discoveryControllerFindCitiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List active public cities
     */
    async discoveryControllerFindCitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CitiesApiResponseDto>> {
        const requestOptions = await this.discoveryControllerFindCitiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CitiesApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List active public cities
     */
    async discoveryControllerFindCities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CitiesApiResponseDto> {
        const response = await this.discoveryControllerFindCitiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for discoveryControllerFindSports without sending the request
     */
    async discoveryControllerFindSportsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List active public sports
     */
    async discoveryControllerFindSportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SportsApiResponseDto>> {
        const requestOptions = await this.discoveryControllerFindSportsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SportsApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List active public sports
     */
    async discoveryControllerFindSports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SportsApiResponseDto> {
        const response = await this.discoveryControllerFindSportsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for discoveryControllerFindTournamentDetail without sending the request
     */
    async discoveryControllerFindTournamentDetailRequestOpts(requestParameters: DiscoveryControllerFindTournamentDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slugOrId'] == null) {
            throw new runtime.RequiredError(
                'slugOrId',
                'Required parameter "slugOrId" was null or undefined when calling discoveryControllerFindTournamentDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tournaments/{slugOrId}`;
        urlPath = urlPath.replace('{slugOrId}', encodeURIComponent(String(requestParameters['slugOrId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a public tournament by slug or UUID
     */
    async discoveryControllerFindTournamentDetailRaw(requestParameters: DiscoveryControllerFindTournamentDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TournamentDetailApiResponseDto>> {
        const requestOptions = await this.discoveryControllerFindTournamentDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentDetailApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a public tournament by slug or UUID
     */
    async discoveryControllerFindTournamentDetail(requestParameters: DiscoveryControllerFindTournamentDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TournamentDetailApiResponseDto> {
        const response = await this.discoveryControllerFindTournamentDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for discoveryControllerFindTournamentFixtures without sending the request
     */
    async discoveryControllerFindTournamentFixturesRequestOpts(requestParameters: DiscoveryControllerFindTournamentFixturesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slugOrId'] == null) {
            throw new runtime.RequiredError(
                'slugOrId',
                'Required parameter "slugOrId" was null or undefined when calling discoveryControllerFindTournamentFixtures().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tournaments/{slugOrId}/fixtures`;
        urlPath = urlPath.replace('{slugOrId}', encodeURIComponent(String(requestParameters['slugOrId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List public fixture sets and results for a published tournament
     */
    async discoveryControllerFindTournamentFixturesRaw(requestParameters: DiscoveryControllerFindTournamentFixturesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicFixtureSetListApiResponseDto>> {
        const requestOptions = await this.discoveryControllerFindTournamentFixturesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicFixtureSetListApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List public fixture sets and results for a published tournament
     */
    async discoveryControllerFindTournamentFixtures(requestParameters: DiscoveryControllerFindTournamentFixturesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicFixtureSetListApiResponseDto> {
        const response = await this.discoveryControllerFindTournamentFixturesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for discoveryControllerFindTournaments without sending the request
     */
    async discoveryControllerFindTournamentsRequestOpts(requestParameters: DiscoveryControllerFindTournamentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['upcomingOnly'] != null) {
            queryParameters['upcoming_only'] = requestParameters['upcomingOnly'];
        }

        if (requestParameters['startsFrom'] != null) {
            queryParameters['starts_from'] = requestParameters['startsFrom'];
        }

        if (requestParameters['startsTo'] != null) {
            queryParameters['starts_to'] = requestParameters['startsTo'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tournaments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List public published tournaments
     */
    async discoveryControllerFindTournamentsRaw(requestParameters: DiscoveryControllerFindTournamentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TournamentListApiResponseDto>> {
        const requestOptions = await this.discoveryControllerFindTournamentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentListApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List public published tournaments
     */
    async discoveryControllerFindTournaments(requestParameters: DiscoveryControllerFindTournamentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TournamentListApiResponseDto> {
        const response = await this.discoveryControllerFindTournamentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const DiscoveryControllerFindTournamentsStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived',
    Blocked: 'blocked'
} as const;
export type DiscoveryControllerFindTournamentsStatusEnum = typeof DiscoveryControllerFindTournamentsStatusEnum[keyof typeof DiscoveryControllerFindTournamentsStatusEnum];
