/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateOrganizerTournamentRequestDto,
    CreateOrganizerTournamentRequestDtoFromJSON,
    CreateOrganizerTournamentRequestDtoToJSON,
} from '../models/CreateOrganizerTournamentRequestDto';
import {
    type CreateTournamentCategoryRequestDto,
    CreateTournamentCategoryRequestDtoFromJSON,
    CreateTournamentCategoryRequestDtoToJSON,
} from '../models/CreateTournamentCategoryRequestDto';
import {
    type OrganizerDashboardApiResponseDto,
    OrganizerDashboardApiResponseDtoFromJSON,
    OrganizerDashboardApiResponseDtoToJSON,
} from '../models/OrganizerDashboardApiResponseDto';
import {
    type OrganizerTournamentApiResponseDto,
    OrganizerTournamentApiResponseDtoFromJSON,
    OrganizerTournamentApiResponseDtoToJSON,
} from '../models/OrganizerTournamentApiResponseDto';
import {
    type OrganizerTournamentCategoryApiResponseDto,
    OrganizerTournamentCategoryApiResponseDtoFromJSON,
    OrganizerTournamentCategoryApiResponseDtoToJSON,
} from '../models/OrganizerTournamentCategoryApiResponseDto';
import {
    type OrganizerTournamentCategoryListApiResponseDto,
    OrganizerTournamentCategoryListApiResponseDtoFromJSON,
    OrganizerTournamentCategoryListApiResponseDtoToJSON,
} from '../models/OrganizerTournamentCategoryListApiResponseDto';
import {
    type OrganizerTournamentListApiResponseDto,
    OrganizerTournamentListApiResponseDtoFromJSON,
    OrganizerTournamentListApiResponseDtoToJSON,
} from '../models/OrganizerTournamentListApiResponseDto';
import {
    type UpdateOrganizerTournamentRequestDto,
    UpdateOrganizerTournamentRequestDtoFromJSON,
    UpdateOrganizerTournamentRequestDtoToJSON,
} from '../models/UpdateOrganizerTournamentRequestDto';
import {
    type UpdateTournamentCategoryRequestDto,
    UpdateTournamentCategoryRequestDtoFromJSON,
    UpdateTournamentCategoryRequestDtoToJSON,
} from '../models/UpdateTournamentCategoryRequestDto';

export interface OrganizerTournamentsControllerCreateCategoryRequest {
    id: string;
    createTournamentCategoryRequestDto: CreateTournamentCategoryRequestDto;
}

export interface OrganizerTournamentsControllerCreateTournamentRequest {
    createOrganizerTournamentRequestDto: CreateOrganizerTournamentRequestDto;
}

export interface OrganizerTournamentsControllerDeleteCategoryRequest {
    id: string;
    categoryId: string;
}

export interface OrganizerTournamentsControllerFindCategoriesRequest {
    id: string;
}

export interface OrganizerTournamentsControllerFindTournamentRequest {
    id: string;
}

export interface OrganizerTournamentsControllerFindTournamentsRequest {
    status?: OrganizerTournamentsControllerFindTournamentsStatusEnum;
    sport?: string;
    search?: string;
    page?: number;
    limit?: number;
}

export interface OrganizerTournamentsControllerPublishTournamentRequest {
    id: string;
}

export interface OrganizerTournamentsControllerUnpublishTournamentRequest {
    id: string;
}

export interface OrganizerTournamentsControllerUpdateCategoryRequest {
    id: string;
    categoryId: string;
    updateTournamentCategoryRequestDto: UpdateTournamentCategoryRequestDto;
}

export interface OrganizerTournamentsControllerUpdateTournamentRequest {
    id: string;
    updateOrganizerTournamentRequestDto: UpdateOrganizerTournamentRequestDto;
}

/**
 * 
 */
export class OrganizerTournamentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for organizerTournamentsControllerCreateCategory without sending the request
     */
    async organizerTournamentsControllerCreateCategoryRequestOpts(requestParameters: OrganizerTournamentsControllerCreateCategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerCreateCategory().'
            );
        }

        if (requestParameters['createTournamentCategoryRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createTournamentCategoryRequestDto',
                'Required parameter "createTournamentCategoryRequestDto" was null or undefined when calling organizerTournamentsControllerCreateCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/categories`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTournamentCategoryRequestDtoToJSON(requestParameters['createTournamentCategoryRequestDto']),
        };
    }

    /**
     * Create a category for one owned organizer tournament
     */
    async organizerTournamentsControllerCreateCategoryRaw(requestParameters: OrganizerTournamentsControllerCreateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentCategoryApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerCreateCategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentCategoryApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a category for one owned organizer tournament
     */
    async organizerTournamentsControllerCreateCategory(requestParameters: OrganizerTournamentsControllerCreateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentCategoryApiResponseDto> {
        const response = await this.organizerTournamentsControllerCreateCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerCreateTournament without sending the request
     */
    async organizerTournamentsControllerCreateTournamentRequestOpts(requestParameters: OrganizerTournamentsControllerCreateTournamentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrganizerTournamentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createOrganizerTournamentRequestDto',
                'Required parameter "createOrganizerTournamentRequestDto" was null or undefined when calling organizerTournamentsControllerCreateTournament().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizerTournamentRequestDtoToJSON(requestParameters['createOrganizerTournamentRequestDto']),
        };
    }

    /**
     * Create a draft tournament for the current organizer
     */
    async organizerTournamentsControllerCreateTournamentRaw(requestParameters: OrganizerTournamentsControllerCreateTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerCreateTournamentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a draft tournament for the current organizer
     */
    async organizerTournamentsControllerCreateTournament(requestParameters: OrganizerTournamentsControllerCreateTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentApiResponseDto> {
        const response = await this.organizerTournamentsControllerCreateTournamentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerDeleteCategory without sending the request
     */
    async organizerTournamentsControllerDeleteCategoryRequestOpts(requestParameters: OrganizerTournamentsControllerDeleteCategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerDeleteCategory().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling organizerTournamentsControllerDeleteCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/categories/{categoryId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{categoryId}', encodeURIComponent(String(requestParameters['categoryId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deactivate one category for an owned organizer tournament
     */
    async organizerTournamentsControllerDeleteCategoryRaw(requestParameters: OrganizerTournamentsControllerDeleteCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentCategoryApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerDeleteCategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentCategoryApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Deactivate one category for an owned organizer tournament
     */
    async organizerTournamentsControllerDeleteCategory(requestParameters: OrganizerTournamentsControllerDeleteCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentCategoryApiResponseDto> {
        const response = await this.organizerTournamentsControllerDeleteCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerFindCategories without sending the request
     */
    async organizerTournamentsControllerFindCategoriesRequestOpts(requestParameters: OrganizerTournamentsControllerFindCategoriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerFindCategories().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/categories`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List categories for one owned organizer tournament
     */
    async organizerTournamentsControllerFindCategoriesRaw(requestParameters: OrganizerTournamentsControllerFindCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentCategoryListApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerFindCategoriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentCategoryListApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List categories for one owned organizer tournament
     */
    async organizerTournamentsControllerFindCategories(requestParameters: OrganizerTournamentsControllerFindCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentCategoryListApiResponseDto> {
        const response = await this.organizerTournamentsControllerFindCategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerFindTournament without sending the request
     */
    async organizerTournamentsControllerFindTournamentRequestOpts(requestParameters: OrganizerTournamentsControllerFindTournamentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerFindTournament().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one owned organizer tournament
     */
    async organizerTournamentsControllerFindTournamentRaw(requestParameters: OrganizerTournamentsControllerFindTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerFindTournamentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get one owned organizer tournament
     */
    async organizerTournamentsControllerFindTournament(requestParameters: OrganizerTournamentsControllerFindTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentApiResponseDto> {
        const response = await this.organizerTournamentsControllerFindTournamentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerFindTournaments without sending the request
     */
    async organizerTournamentsControllerFindTournamentsRequestOpts(requestParameters: OrganizerTournamentsControllerFindTournamentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List current organizer tournaments
     */
    async organizerTournamentsControllerFindTournamentsRaw(requestParameters: OrganizerTournamentsControllerFindTournamentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentListApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerFindTournamentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentListApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * List current organizer tournaments
     */
    async organizerTournamentsControllerFindTournaments(requestParameters: OrganizerTournamentsControllerFindTournamentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentListApiResponseDto> {
        const response = await this.organizerTournamentsControllerFindTournamentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerGetDashboard without sending the request
     */
    async organizerTournamentsControllerGetDashboardRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/dashboard`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current organizer dashboard summary
     */
    async organizerTournamentsControllerGetDashboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerDashboardApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerGetDashboardRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerDashboardApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current organizer dashboard summary
     */
    async organizerTournamentsControllerGetDashboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerDashboardApiResponseDto> {
        const response = await this.organizerTournamentsControllerGetDashboardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerPublishTournament without sending the request
     */
    async organizerTournamentsControllerPublishTournamentRequestOpts(requestParameters: OrganizerTournamentsControllerPublishTournamentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerPublishTournament().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/publish`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Publish one owned organizer tournament
     */
    async organizerTournamentsControllerPublishTournamentRaw(requestParameters: OrganizerTournamentsControllerPublishTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerPublishTournamentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Publish one owned organizer tournament
     */
    async organizerTournamentsControllerPublishTournament(requestParameters: OrganizerTournamentsControllerPublishTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentApiResponseDto> {
        const response = await this.organizerTournamentsControllerPublishTournamentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerUnpublishTournament without sending the request
     */
    async organizerTournamentsControllerUnpublishTournamentRequestOpts(requestParameters: OrganizerTournamentsControllerUnpublishTournamentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerUnpublishTournament().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/unpublish`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Move one owned organizer tournament back to draft
     */
    async organizerTournamentsControllerUnpublishTournamentRaw(requestParameters: OrganizerTournamentsControllerUnpublishTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerUnpublishTournamentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Move one owned organizer tournament back to draft
     */
    async organizerTournamentsControllerUnpublishTournament(requestParameters: OrganizerTournamentsControllerUnpublishTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentApiResponseDto> {
        const response = await this.organizerTournamentsControllerUnpublishTournamentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerUpdateCategory without sending the request
     */
    async organizerTournamentsControllerUpdateCategoryRequestOpts(requestParameters: OrganizerTournamentsControllerUpdateCategoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerUpdateCategory().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling organizerTournamentsControllerUpdateCategory().'
            );
        }

        if (requestParameters['updateTournamentCategoryRequestDto'] == null) {
            throw new runtime.RequiredError(
                'updateTournamentCategoryRequestDto',
                'Required parameter "updateTournamentCategoryRequestDto" was null or undefined when calling organizerTournamentsControllerUpdateCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}/categories/{categoryId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{categoryId}', encodeURIComponent(String(requestParameters['categoryId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTournamentCategoryRequestDtoToJSON(requestParameters['updateTournamentCategoryRequestDto']),
        };
    }

    /**
     * Update one category for an owned organizer tournament
     */
    async organizerTournamentsControllerUpdateCategoryRaw(requestParameters: OrganizerTournamentsControllerUpdateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentCategoryApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerUpdateCategoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentCategoryApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update one category for an owned organizer tournament
     */
    async organizerTournamentsControllerUpdateCategory(requestParameters: OrganizerTournamentsControllerUpdateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentCategoryApiResponseDto> {
        const response = await this.organizerTournamentsControllerUpdateCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizerTournamentsControllerUpdateTournament without sending the request
     */
    async organizerTournamentsControllerUpdateTournamentRequestOpts(requestParameters: OrganizerTournamentsControllerUpdateTournamentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizerTournamentsControllerUpdateTournament().'
            );
        }

        if (requestParameters['updateOrganizerTournamentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizerTournamentRequestDto',
                'Required parameter "updateOrganizerTournamentRequestDto" was null or undefined when calling organizerTournamentsControllerUpdateTournament().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizer/tournaments/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizerTournamentRequestDtoToJSON(requestParameters['updateOrganizerTournamentRequestDto']),
        };
    }

    /**
     * Update one owned organizer tournament
     */
    async organizerTournamentsControllerUpdateTournamentRaw(requestParameters: OrganizerTournamentsControllerUpdateTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizerTournamentApiResponseDto>> {
        const requestOptions = await this.organizerTournamentsControllerUpdateTournamentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerTournamentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update one owned organizer tournament
     */
    async organizerTournamentsControllerUpdateTournament(requestParameters: OrganizerTournamentsControllerUpdateTournamentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizerTournamentApiResponseDto> {
        const response = await this.organizerTournamentsControllerUpdateTournamentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const OrganizerTournamentsControllerFindTournamentsStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived',
    Blocked: 'blocked'
} as const;
export type OrganizerTournamentsControllerFindTournamentsStatusEnum = typeof OrganizerTournamentsControllerFindTournamentsStatusEnum[keyof typeof OrganizerTournamentsControllerFindTournamentsStatusEnum];
