/* tslint:disable */
/* eslint-disable */
/**
 * MatchFlow Arena API
 * API contract for MatchFlow Arena.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockCompletePaymentRequestDto,
    MockCompletePaymentRequestDtoFromJSON,
    MockCompletePaymentRequestDtoToJSON,
} from '../models/MockCompletePaymentRequestDto';
import {
    type PaymentIntentApiResponseDto,
    PaymentIntentApiResponseDtoFromJSON,
    PaymentIntentApiResponseDtoToJSON,
} from '../models/PaymentIntentApiResponseDto';
import {
    type RegistrationPaymentDetailApiResponseDto,
    RegistrationPaymentDetailApiResponseDtoFromJSON,
    RegistrationPaymentDetailApiResponseDtoToJSON,
} from '../models/RegistrationPaymentDetailApiResponseDto';
import {
    type VerifyRazorpayPaymentRequestDto,
    VerifyRazorpayPaymentRequestDtoFromJSON,
    VerifyRazorpayPaymentRequestDtoToJSON,
} from '../models/VerifyRazorpayPaymentRequestDto';

export interface PaymentsControllerCompleteMockPaymentRequest {
    mockCompletePaymentRequestDto: MockCompletePaymentRequestDto;
}

export interface PaymentsControllerCreatePaymentIntentRequest {
    registrationId: string;
}

export interface PaymentsControllerFindRegistrationPaymentRequest {
    registrationId: string;
}

export interface PaymentsControllerHandleWebhookRequest {
    provider: string;
    xRazorpaySignature?: string;
    xRazorpayEventId?: string;
}

export interface PaymentsControllerVerifyRazorpayPaymentRequest {
    registrationId: string;
    verifyRazorpayPaymentRequestDto: VerifyRazorpayPaymentRequestDto;
}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for paymentsControllerCompleteMockPayment without sending the request
     */
    async paymentsControllerCompleteMockPaymentRequestOpts(requestParameters: PaymentsControllerCompleteMockPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockCompletePaymentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'mockCompletePaymentRequestDto',
                'Required parameter "mockCompletePaymentRequestDto" was null or undefined when calling paymentsControllerCompleteMockPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/payments/mock/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockCompletePaymentRequestDtoToJSON(requestParameters['mockCompletePaymentRequestDto']),
        };
    }

    /**
     * Complete a mock payment intent for the current player in non-production environments
     */
    async paymentsControllerCompleteMockPaymentRaw(requestParameters: PaymentsControllerCompleteMockPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentApiResponseDto>> {
        const requestOptions = await this.paymentsControllerCompleteMockPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Complete a mock payment intent for the current player in non-production environments
     */
    async paymentsControllerCompleteMockPayment(requestParameters: PaymentsControllerCompleteMockPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentApiResponseDto> {
        const response = await this.paymentsControllerCompleteMockPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsControllerCreatePaymentIntent without sending the request
     */
    async paymentsControllerCreatePaymentIntentRequestOpts(requestParameters: PaymentsControllerCreatePaymentIntentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registrationId'] == null) {
            throw new runtime.RequiredError(
                'registrationId',
                'Required parameter "registrationId" was null or undefined when calling paymentsControllerCreatePaymentIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/me/registrations/{registrationId}/payment-intent`;
        urlPath = urlPath.replace('{registrationId}', encodeURIComponent(String(requestParameters['registrationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create or return an online payment intent for the current player\'s registration
     */
    async paymentsControllerCreatePaymentIntentRaw(requestParameters: PaymentsControllerCreatePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentApiResponseDto>> {
        const requestOptions = await this.paymentsControllerCreatePaymentIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create or return an online payment intent for the current player\'s registration
     */
    async paymentsControllerCreatePaymentIntent(requestParameters: PaymentsControllerCreatePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentApiResponseDto> {
        const response = await this.paymentsControllerCreatePaymentIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsControllerFindRegistrationPayment without sending the request
     */
    async paymentsControllerFindRegistrationPaymentRequestOpts(requestParameters: PaymentsControllerFindRegistrationPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registrationId'] == null) {
            throw new runtime.RequiredError(
                'registrationId',
                'Required parameter "registrationId" was null or undefined when calling paymentsControllerFindRegistrationPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/me/registrations/{registrationId}/payment`;
        urlPath = urlPath.replace('{registrationId}', encodeURIComponent(String(requestParameters['registrationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a safe current-player registration payment summary
     */
    async paymentsControllerFindRegistrationPaymentRaw(requestParameters: PaymentsControllerFindRegistrationPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegistrationPaymentDetailApiResponseDto>> {
        const requestOptions = await this.paymentsControllerFindRegistrationPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationPaymentDetailApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a safe current-player registration payment summary
     */
    async paymentsControllerFindRegistrationPayment(requestParameters: PaymentsControllerFindRegistrationPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegistrationPaymentDetailApiResponseDto> {
        const response = await this.paymentsControllerFindRegistrationPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsControllerHandleWebhook without sending the request
     */
    async paymentsControllerHandleWebhookRequestOpts(requestParameters: PaymentsControllerHandleWebhookRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling paymentsControllerHandleWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRazorpaySignature'] != null) {
            headerParameters['x-razorpay-signature'] = String(requestParameters['xRazorpaySignature']);
        }

        if (requestParameters['xRazorpayEventId'] != null) {
            headerParameters['x-razorpay-event-id'] = String(requestParameters['xRazorpayEventId']);
        }


        let urlPath = `/payments/webhooks/{provider}`;
        urlPath = urlPath.replace('{provider}', encodeURIComponent(String(requestParameters['provider'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Provider-neutral payment webhook endpoint
     */
    async paymentsControllerHandleWebhookRaw(requestParameters: PaymentsControllerHandleWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentApiResponseDto>> {
        const requestOptions = await this.paymentsControllerHandleWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Provider-neutral payment webhook endpoint
     */
    async paymentsControllerHandleWebhook(requestParameters: PaymentsControllerHandleWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentApiResponseDto> {
        const response = await this.paymentsControllerHandleWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsControllerVerifyRazorpayPayment without sending the request
     */
    async paymentsControllerVerifyRazorpayPaymentRequestOpts(requestParameters: PaymentsControllerVerifyRazorpayPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registrationId'] == null) {
            throw new runtime.RequiredError(
                'registrationId',
                'Required parameter "registrationId" was null or undefined when calling paymentsControllerVerifyRazorpayPayment().'
            );
        }

        if (requestParameters['verifyRazorpayPaymentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'verifyRazorpayPaymentRequestDto',
                'Required parameter "verifyRazorpayPaymentRequestDto" was null or undefined when calling paymentsControllerVerifyRazorpayPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/me/registrations/{registrationId}/payment/verify`;
        urlPath = urlPath.replace('{registrationId}', encodeURIComponent(String(requestParameters['registrationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRazorpayPaymentRequestDtoToJSON(requestParameters['verifyRazorpayPaymentRequestDto']),
        };
    }

    /**
     * Verify Razorpay Checkout payment success for the current player\'s registration
     */
    async paymentsControllerVerifyRazorpayPaymentRaw(requestParameters: PaymentsControllerVerifyRazorpayPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentApiResponseDto>> {
        const requestOptions = await this.paymentsControllerVerifyRazorpayPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentApiResponseDtoFromJSON(jsonValue));
    }

    /**
     * Verify Razorpay Checkout payment success for the current player\'s registration
     */
    async paymentsControllerVerifyRazorpayPayment(requestParameters: PaymentsControllerVerifyRazorpayPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentApiResponseDto> {
        const response = await this.paymentsControllerVerifyRazorpayPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
